import {$,node,setText,formatTime} from "./common.js";
let configRevision="",configDirty=false,localConfig=null,selected=null,working=false;
const get=async(url)=>{const r=await fetch(url,{cache:"no-store",headers:{Accept:"application/json"}});const v=await r.json().catch(()=>({}));if(!r.ok)throw new Error(v.error?.message||v.error||r.statusText);return v};
const send=async(url,method,data)=>{const r=await fetch(url,{method,cache:"no-store",headers:{"Content-Type":"application/json",Accept:"application/json"},body:data==null?undefined:JSON.stringify(data)});const v=await r.json().catch(()=>({}));if(!r.ok)throw new Error(v.error?.message||v.error||r.statusText);return v};
function status(message,error=false){const el=$("node-status");if(el){el.textContent=message;el.className="write-status "+(error?"error":"success")}}
function btn(label,action){const b=node("button","small-button",label);b.type="button";b.addEventListener("click",async()=>{if(working)return;working=true;b.disabled=true;try{await action()}catch(e){status(e.message,true)}finally{working=false;b.disabled=false}});return b}
function line(parent,...parts){const el=node("div","node-line");for(const part of parts){el.append(typeof part==="string"?document.createTextNode(part):part)}parent.append(el);return el}
function clear(id,empty){const root=$(id);if(!root)return null;root.replaceChildren();if(empty)root.append(node("span","node-muted",empty));return root}
function item(name,tag){const wrap=node("article","node-card"),header=node("div","node-card-header"),title=node("strong","",name);header.append(title,node("span","node-tag",tag));wrap.append(header);return wrap}
function grantPicker(container){const projects=(localConfig?.workspaces||[]).flatMap(w=>(w.projects||[]).map(p=>({workspace:w.id,project:p.id,config:p})));if(!projects.length){container.append(node("span","node-muted","没有可授权的本地 Project"));return ()=>[];}const rows=[];for(const project of projects){const box=node("label","node-grant"),enable=document.createElement("input");enable.type="checkbox";box.append(enable,document.createTextNode(" "+project.workspace+"/"+project.project));const toggles={};for(const [key,allowed] of [["read",true],["write",project.config.allow_write],["execute",project.config.allow_exec],["git",project.config.allow_git_commit]]){const entry=node("span","node-grant-permission"),check=document.createElement("input");check.type="checkbox";check.disabled=!allowed;check.checked=key==="read";entry.append(check,document.createTextNode(" "+key));box.append(entry);toggles[key]=check;}container.append(box);rows.push({project,enable,toggles});}return()=>rows.filter(x=>x.enable.checked).map(x=>({workspace:x.project.workspace,project:x.project.project,read:x.toggles.read.checked,write:x.toggles.write.checked,execute:x.toggles.execute.checked,git:x.toggles.git.checked}))}
async function doApprove(p,grants){if(!window.confirm("请在两台设备本地核对验证码 "+p.code+" 一致，并确认授权 "+p.name+"？"))return;await send("/api/nodes/approve","POST",{id:p.id,grants});status("已批准节点 "+p.name+"；对方也必须在本地批准");await refreshNodes()}
function renderPending(items){const root=clear("node-pending-list",items.length?"":"没有待确认的配对");for(const p of items){const card=item(p.name,p.role==="parent"?"Outgoing request":"Incoming request");line(card,"Node "+p.node_id+" · "+p.endpoint);const code=node("div","node-pair-code",p.code);card.append(code,node("p","node-muted","两端必须显示相同的六位验证码。未核对前不要批准。"));if(p.role==="child"){const details=node("details","node-grant-details"),summary=node("summary","","Select authorized Projects"),grants=node("div","node-grant-list");details.append(summary,grants);const collect=grantPicker(grants);card.append(details,btn("Approve child grants",()=>doApprove(p,collect())));}else{card.append(btn("Confirm pairing",()=>doApprove(p,[])))}root.append(card);}}
function renderDiscovered(items){const root=clear("node-discovered-list",items.length?"":"没有发现其他节点。可手动输入局域网 IP:Port。");for(const p of items){const card=item(p.name,p.online?"Online":"Offline");line(card,p.node_id+" · "+p.address);card.append(btn("Pair",async()=>{const input=$("node-pair-address");if(input)input.value=p.address;await requestPair(p.address)}));root.append(card)}}
async function remote(nodeId,tool,arguments_={}){const v=await send("/api/nodes/read","POST",{node_id:nodeId,tool,arguments:arguments_});return v}
function detail(title,content){setText("node-remote-title",title);const output=$("node-remote-output");if(output)output.textContent=typeof content==="string"?content:JSON.stringify(content,null,2);const root=$("node-project-detail");if(root)root.hidden=false;}
// Requests are untrusted child-node data: render labels with textContent, never innerHTML.
async function loadRequestHistory(peer,w,p){
 const data=await remote(peer.node_id,"request_history",{workspace:w,project:p,limit:20});
 if(!selected||selected.node!==peer.node_id||selected.workspace!==w||selected.project!==p)return;
 const panel=$("node-request-history"),list=clear("node-history-list");
 if(!panel||!list)return;
 panel.hidden=false;
 setText("node-history-summary",(data.requests||[]).length+" recent"+(data.has_more?" · more available":""));
 if(!(data.requests||[]).length){list.append(node("span","node-muted","没有可显示的新请求记录。旧请求仍可通过 Request status 按 ID 查询。"));return;}
 for(const record of data.requests){
  const row=node("div","node-history-row"),meta=node("div","node-history-meta");
  const tag=node("span","node-history-state",String(record.state||"unknown"));tag.dataset.state=String(record.state||"unknown");
  const identity=node("strong","",String(record.request_id||""));
  const subtitle=node("span","node-muted",String(record.tool||"unknown")+" · "+(record.updated?new Date(record.updated*1000).toLocaleString():"time unavailable"));
  meta.append(identity,subtitle);
  const actions=node("div","node-history-actions");
  actions.append(tag);
  if(record.job_status){const jobTag=node("span","node-history-state","Job: "+record.job_status);jobTag.dataset.state=String(record.job_status);actions.append(jobTag);}
  actions.append(btn("Inspect",async()=>detail(w+"/"+p+" · Request "+record.request_id,await remote(peer.node_id,"request_status",{workspace:w,project:p,request_id:record.request_id}))));
  row.append(meta,actions);list.append(row);
 }
}

async function openProject(peer,w,p){selected={node:peer.node_id,workspace:w,project:p};const historyRoot=$("node-request-history");if(historyRoot)historyRoot.hidden=true;if($("node-remote-args"))$("node-remote-args").value=JSON.stringify({program:"git",args:["status"],request_id:crypto.randomUUID()},null,2);const root=clear("node-remote-buttons");if(!root)return;const args=()=>({workspace:w,project:p});root.append(btn("Request history",()=>loadRequestHistory(peer,w,p)),btn("Request status",async()=>{const id=window.prompt("请输入此前远程操作的 request_id");if(!id)return;detail(w+"/"+p+" · Request "+id,await remote(peer.node_id,"request_status",{...args(),request_id:id.trim()}))}),btn("Inspect",async()=>detail(w+"/"+p,await remote(peer.node_id,"inspect_project",args()))),btn("Git status",async()=>detail(w+"/"+p+" · Git",await remote(peer.node_id,"git_status",args()))),btn("List files",async()=>{const path=$("node-remote-path").value||".";detail(w+"/"+p+" · "+path,await remote(peer.node_id,"list_directory",{...args(),path,limit:100}))}),btn("Read file",async()=>{const path=$("node-remote-path").value.trim();if(!path||path===".")throw new Error("请填写相对文件路径");const result=await remote(peer.node_id,"read_file",{...args(),path,start_line:1,max_lines:200});detail(w+"/"+p+"/"+path,result)}));detail("Selected "+w+"/"+p,"选择文件或 Git 操作。子节点会再次验证该 Project 的读取授权。")}
async function browse(peer){const historyRoot=$("node-request-history");if(historyRoot)historyRoot.hidden=true;const v=await remote(peer.node_id,"list_workspaces",{});const root=$("node-project-detail");if(root)root.hidden=false;const actions=clear("node-remote-buttons");if(!actions)return;for(const workspace of v.workspaces||[]){const projects=await remote(peer.node_id,"list_projects",{workspace:workspace.id});for(const p of projects.projects||[]){actions.append(btn(workspace.id+"/"+p.id,()=>openProject(peer,workspace.id,p.id)))}}detail(peer.name+" · Projects",actions.children.length?"选择左侧 Project 查看详情。":"没有授权可见的 Project")}
async function revoke(peer){if(!window.confirm("撤销节点 "+peer.name+" 的本地配对？两端均须撤销才能完全解除双向信任。"))return;await send("/api/nodes/peers/"+encodeURIComponent(peer.node_id),"DELETE",{});status("本地已撤销 "+peer.name);if(selected?.node===peer.node_id){selected=null;const detailRoot=$("node-project-detail");if(detailRoot)detailRoot.hidden=true;}await refreshNodes()}
function renderTrusted(items){const root=clear("node-trusted-list",items.length?"":"尚无已配对节点");for(const p of items){const card=item(p.name,p.role==="parent"?"Child (managed)":"Parent (authorized)");line(card,p.node_id+" · "+p.endpoint);line(card,p.discovery_online?"Recently discovered on LAN":"Not seen in recent LAN discovery · manual connection may still work");if(p.role==="parent")card.append(btn("Browse Projects",()=>browse(p)));else line(card,"Granted "+(p.grants||[]).map(g=>g.workspace+"/"+g.project).join(", "));card.append(btn("Revoke locally",()=>revoke(p)));root.append(card)}}
async function submitRemoteOperation(event){event.preventDefault();if(!selected){status("请先选择配对节点的 Project",true);return;}const tool=$("node-remote-tool").value;let payload;try{payload=JSON.parse($("node-remote-args").value||"{}");if(!payload||Array.isArray(payload)||typeof payload!=="object")throw new Error("Arguments 必须是 JSON object");if((payload.workspace&&payload.workspace!==selected.workspace)||(payload.project&&payload.project!==selected.project))throw new Error("不能更改当前选中的 Workspace/Project");}catch(e){status("远程参数错误："+e.message,true);return;}payload.workspace=selected.workspace;payload.project=selected.project;const requestId=(tool==="run_command"&&typeof payload.request_id==="string"&&payload.request_id.trim())?payload.request_id.trim():crypto.randomUUID();const summary=`${selected.node} / ${selected.workspace}/${selected.project} / ${tool}`;if(!window.confirm(`确认向子节点执行 ${summary}？\n\n远程修改可能继续在子节点运行，即使当前网络连接断开。若执行超时，请先查询原任务状态，不要更换 request_id 重复运行。`))return;const button=event.currentTarget.querySelector("button[type=submit]");button.disabled=true;try{const result=await send("/api/nodes/write","POST",{node_id:selected.node,tool,arguments:payload,confirm:true,request_id:requestId});detail(summary,result);status(`远程操作 ${tool} 已返回结果；request_id=${requestId}，Job 可继续查询`);}catch(e){status(`远程操作未确认：${e.message}；request_id=${requestId}。请使用 Request status 查询，禁止盲目重放。`,true)}finally{button.disabled=false}}
async function requestPair(address){const result=await send("/api/nodes/pair","POST",{address});status("已发送配对申请。两端验证码："+result.code+"；请在子节点 Nodes 页面核对。");await refreshNodes();}
export async function refreshNodes(){if(!$("node-identity"))return;try{const [discovery,peers,pending,config]=await Promise.all([get("/api/nodes"),get("/api/nodes/peers"),get("/api/nodes/pending"),get("/api/config")]);localConfig=config;setText("node-identity",discovery.enabled?"Local node "+discovery.name+" · "+discovery.node_id+" · "+discovery.listen:"Transfer disabled · 在 Config 中启用并重启");renderDiscovered(discovery.peers||[]);renderPending(pending.pending||[]);renderTrusted(peers.peers||[]);setText("node-updated","Updated "+formatTime(Math.floor(Date.now()/1000)));}catch(e){status("Nodes 刷新失败："+e.message,true)}}
export function renderTransferEditor(config){const form=$("transfer-editor");if(!form||configDirty)return;const c=config.transfer||{};for(const key of ["enabled","advertise","discover"])form.elements.namedItem(key).checked=!!c[key];form.elements.namedItem("display_name").value=c.display_name||"EndlessVibe";form.elements.namedItem("listen").value=c.listen||"0.0.0.0:20002";configRevision=config.revision||"";const display=$("config-transfer");if(display){display.replaceChildren();for(const [key,value] of Object.entries(c)){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=key;dd.textContent=typeof value==="object"?JSON.stringify(value):String(value);display.append(dt,dd);}}}
async function saveTransfer(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector("button[type=submit]");if(!form.reportValidity())return;const payload={expected_revision:configRevision,display_name:form.elements.namedItem("display_name").value.trim(),listen:form.elements.namedItem("listen").value.trim()};for(const key of ["enabled","advertise","discover"])payload[key]=form.elements.namedItem(key).checked;button.disabled=true;try{await send("/api/config/transfer","PUT",payload);configDirty=false;const statusEl=$("transfer-editor-status");if(statusEl){statusEl.textContent="Transfer 配置已保存。重启 EndlessVibe 后生效。";statusEl.className="write-status success";}const cfg=await get("/api/config");renderTransferEditor(cfg)}catch(e){const el=$("transfer-editor-status");if(el){el.textContent="保存失败："+e.message;el.className="write-status error";}}finally{button.disabled=false}}
export function initNodes(){const pairForm=$("node-pair-form");pairForm?.addEventListener("submit",async event=>{event.preventDefault();const address=$("node-pair-address").value.trim();try{await requestPair(address)}catch(e){status(e.message,true)}});$("node-refresh")?.addEventListener("click",refreshNodes);$("node-remote-operation")?.addEventListener("submit",submitRemoteOperation);$("node-remote-tool")?.addEventListener("change",()=>{const tool=$("node-remote-tool")?.value;const template=tool==="run_command"?{program:"git",args:["status"],request_id:"unique-request-id"}:tool==="get_job"||tool==="cancel_job"?{job_id:"child-job-id"}:tool==="get_job_output"?{job_id:"child-job-id",offset:0,limit:8192}:tool==="create_directory"?{path:"new-folder"}:tool==="write_file"?{path:"file.txt",content:"text",expected_sha256:"MISSING"}:tool==="apply_patch"?{path:"file.txt",expected_sha256:"SHA256",edits:[{old_text:"before",new_text:"after",expected_occurrences:1}]}:{paths:["file.txt"],message:"feat: update",expected_head:"HEAD",expected_diff_sha256:"DIFF_HASH"};const input=$("node-remote-args");if(input)input.value=JSON.stringify(template,null,2);});$("transfer-editor")?.addEventListener("submit",saveTransfer);$("transfer-editor")?.addEventListener("input",()=>{configDirty=true;const el=$("transfer-editor-status");if(el){el.textContent="Transfer 设置有未保存的修改";el.className="write-status pending";}});if(location.pathname==="/nodes"){refreshNodes();setInterval(()=>{if(!document.hidden)refreshNodes()},10000);}}
