use crate::{runtime::Runtime,util,workspace::Project};
use anyhow::{bail,Context,Result};
use serde_json::{json,Value};
use std::{collections::BTreeSet,os::unix::fs::MetadataExt,path::PathBuf};
use super::repo::{args,good,head,oid,preflight,status,Environment};

pub(super) struct Change{pub(super) path:String,pub(super) bytes:Option<Vec<u8>>,pub(super) mode:String,pub(super) oid:String}
pub(super) struct Preview{pub(super) _temp:tempfile::TempDir,pub(super) index:PathBuf,pub(super) head:String,pub(super) paths:Vec<String>,pub(super) diff:String,pub(super) review:String,pub(super) changes:Vec<Change>}

async fn selected(rt:&Runtime,w:&Project,paths:Vec<String>)->Result<Vec<String>>{let mut paths:BTreeSet<String>=paths.into_iter().collect();if paths.is_empty(){let s=status(rt,w).await?;if let Some(entries)=s["entries"].as_array(){for e in entries{if let Some(p)=e["path"].as_str(){paths.insert(p.to_owned());}if let Some(p)=e["original_path"].as_str(){paths.insert(p.to_owned());}}}}if paths.len()>64{bail!("Select at most 64 exact files per review/commit");}for p in &paths{crate::security::paths::relative(p,false)?;if let Ok(md)=w.root.metadata(p){if !md.is_file()||md.nlink()!=1{bail!("Git review accepts regular files only; symlinks, hardlinks, submodules and directories are refused");}}}Ok(paths.into_iter().collect())}
pub(super) fn index_records(changes:&[Change],hash_len:usize)->Vec<u8>{let mut data=Vec::new();for c in changes{let record=if c.bytes.is_some(){format!("{} {}\t{}\0",c.mode,c.oid,c.path)}else{format!("0 {}\t{}\0","0".repeat(hash_len),c.path)};data.extend_from_slice(record.as_bytes());}data}
pub(super) async fn preview(rt:&Runtime,w:&Project,paths:Vec<String>)->Result<Preview>{let paths=selected(rt,w,paths).await?;let head=head(rt,w).await?;let temp=tempfile::Builder::new().prefix("git-review-").tempdir_in(rt.config.security.data_dir.join("tmp"))?;let index=temp.path().join("index");let objects=temp.path().join("objects");std::fs::create_dir(&objects)?;let env=Environment{index:Some(index.clone()),objects:Some(objects)};let base=if head=="UNBORN"{good(rt,w,args(&["read-tree","--empty"]),&env,None).await?;oid(good(rt,w,args(&["hash-object","-t","tree","-w","--stdin"]),&env,Some(vec![])).await?)?}else{good(rt,w,vec!["read-tree".into(),head.clone()],&env,None).await?;head.clone()};let mut changes=Vec::new();let mut total=0;for path in &paths{let data=w.root.read_optional(path,rt.config.limits.max_file_bytes)?;let(mode,id)=if let Some(bytes)=&data{total+=bytes.len();if total>16*1024*1024{bail!("Review input exceeds 16 MiB; use smaller commits");}let id=oid(good(rt,w,args(&["hash-object","-w","--no-filters","--stdin"]),&env,Some(bytes.clone())).await?)?;let mode=if w.root.metadata(path)?.mode()&0o111!=0{"100755"}else{"100644"};(mode.to_owned(),id)}else{("0".into(),String::new())};changes.push(Change{path:path.clone(),bytes:data,mode,oid:id});}if !changes.is_empty(){good(rt,w,args(&["update-index","-z","--index-info"]),&env,Some(index_records(&changes,base.len()))).await?;}let mut command=args(&["diff","--cached","--binary","--full-index","--no-ext-diff","--no-textconv","--ignore-submodules=all","--no-color"]);command.push(base);command.push("--".into());command.extend(paths.clone());let diff=String::from_utf8(good(rt,w,command,&env,None).await?).context("Git diff is not UTF-8")?;if diff.len()>rt.config.limits.max_output_bytes{bail!("Diff exceeds max_output_bytes; select fewer/smaller files");}let review=util::digest(serde_json::to_vec(&(&head,&paths,&diff))?);Ok(Preview{_temp:temp,index,head,paths,diff,review,changes})}
pub async fn diff(rt:&Runtime,w:&Project,a:crate::tools::types::DiffArgs)->Result<Value>{preflight(rt,w).await?;let p=preview(rt,w,a.paths).await?;Ok(json!({"workspace":w.workspace_id,"project":w.config.id,"paths":p.paths,"head":p.head,"diff_sha256":p.review,"diff":p.diff,"has_changes":!p.diff.is_empty(),"commit_policy":"Pass these exact paths/head/diff_sha256 to git_commit. Selected pre-staged changes are refused; unrelated staging is preserved. Raw file bytes are used (no clean filters/LFS conversion)."}))}
