use super::TransferManager;
use crate::{store::Store,util};
use anyhow::{bail,Context,Result};
use rustls::{client::danger::{ServerCertVerified,ServerCertVerifier,HandshakeSignatureValid},pki_types::{CertificateDer,PrivateKeyDer,PrivatePkcs8KeyDer,ServerName,UnixTime},DigitallySignedStruct,SignatureScheme};
use serde::{Deserialize,Serialize};
use serde_json::{json,Value};
use std::{net::{IpAddr,SocketAddr},sync::Arc,time::Duration};
use tokio::{io::{AsyncRead,AsyncReadExt,AsyncWrite,AsyncWriteExt},net::{TcpListener,TcpStream}};
use tokio_rustls::{TlsAcceptor,TlsConnector};
use tokio_util::sync::CancellationToken;

const MAX_WIRE:usize=2*1024*1024;
const PAIR_TTL:u64=300;
const PAIRS:&str="transfer_peers";
const PENDING:&str="transfer_pending";
#[derive(Clone,Debug,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Grant{pub workspace:String,pub project:String,pub read:bool,pub write:bool,pub execute:bool,pub git:bool}
#[derive(Clone,Debug,Serialize,Deserialize)]
pub struct Peer{pub node_id:String,pub name:String,pub endpoint:SocketAddr,pub cert_sha:String,pub role:String,#[serde(default)]pub token:String,#[serde(default)]pub token_hash:String,#[serde(default)]pub grants:Vec<Grant>,pub paired_at:u64}
#[derive(Clone,Debug,Serialize,Deserialize)]
pub struct Pending{pub id:String,pub node_id:String,pub name:String,pub endpoint:SocketAddr,pub cert_sha:String,pub token_hash:String,#[serde(default)]pub token:String,pub code:String,pub role:String,pub created:u64}
#[derive(Clone,Debug,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PairApprove{pub id:String,#[serde(default)]pub grants:Vec<Grant>}
#[derive(Clone,Debug,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PairStart{pub address:SocketAddr}
#[derive(Clone,Debug,Serialize,Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Wire{pub kind:String,pub node_id:String,#[serde(default)]pub name:String,#[serde(default)]pub id:String,#[serde(default)]pub token:String,#[serde(default)]pub tool:String,#[serde(default)]pub args:Value}
#[derive(Debug)]
struct PairVerifier{pin:Option<String>}
impl ServerCertVerifier for PairVerifier{
 fn verify_server_cert(&self,cert:&CertificateDer<'_>,_:&[CertificateDer<'_>],_:&ServerName<'_>,_:&[u8],_:UnixTime)->std::result::Result<ServerCertVerified,rustls::Error>{if self.pin.as_deref().is_some_and(|p|p!=util::digest(cert.as_ref())){return Err(rustls::Error::General("Transfer certificate fingerprint changed".into()));}Ok(ServerCertVerified::assertion())}
 fn verify_tls12_signature(&self,msg:&[u8],cert:&CertificateDer<'_>,dss:&DigitallySignedStruct)->std::result::Result<HandshakeSignatureValid,rustls::Error>{rustls::crypto::verify_tls12_signature(msg,cert,dss,&rustls::crypto::ring::default_provider().signature_verification_algorithms)}
 fn verify_tls13_signature(&self,msg:&[u8],cert:&CertificateDer<'_>,dss:&DigitallySignedStruct)->std::result::Result<HandshakeSignatureValid,rustls::Error>{rustls::crypto::verify_tls13_signature(msg,cert,dss,&rustls::crypto::ring::default_provider().signature_verification_algorithms)}
 fn supported_verify_schemes(&self)->Vec<SignatureScheme>{rustls::crypto::ring::default_provider().signature_verification_algorithms.supported_schemes()}
}
fn tls_server_config(db:&Store)->Result<Arc<rustls::ServerConfig>>{
 let pair:Option<(Vec<u8>,Vec<u8>)>=db.get("transfer_meta","tls_identity")?;
 let (cert,key)=if let Some(v)=pair{v}else{let generated=rcgen::generate_simple_self_signed(vec!["endlessvibe.local".into()]).context("Generate Transfer TLS identity")?;let cert=generated.cert.der().to_vec();let key=generated.key_pair.serialize_der();db.put("transfer_meta","tls_identity",&(cert.clone(),key.clone()),0)?;(cert,key)};
 let server=rustls::ServerConfig::builder_with_provider(Arc::new(rustls::crypto::ring::default_provider())).with_protocol_versions(&[&rustls::version::TLS13])?.with_no_client_auth().with_single_cert(vec![CertificateDer::from(cert)],PrivateKeyDer::Pkcs8(PrivatePkcs8KeyDer::from(key)))?;Ok(Arc::new(server))
}
fn tls_client_config(pin:Option<String>)->Result<Arc<rustls::ClientConfig>>{let client=rustls::ClientConfig::builder_with_provider(Arc::new(rustls::crypto::ring::default_provider())).with_protocol_versions(&[&rustls::version::TLS13])?.dangerous().with_custom_certificate_verifier(Arc::new(PairVerifier{pin})).with_no_client_auth();Ok(Arc::new(client))}
async fn send<W:AsyncWrite+Unpin>(stream:&mut W,data:&Value)->Result<()>{let bytes=serde_json::to_vec(data)?;if bytes.len()>MAX_WIRE{bail!("Transfer request exceeds frame limit");}stream.write_u32(bytes.len() as u32).await?;stream.write_all(&bytes).await?;stream.flush().await?;Ok(())}
async fn recv<R:AsyncRead+Unpin>(stream:&mut R)->Result<Value>{let length=stream.read_u32().await? as usize;if length==0||length>MAX_WIRE{bail!("Transfer frame length exceeds limit");}let mut bytes=vec![0u8;length];stream.read_exact(&mut bytes).await?;Ok(serde_json::from_slice(&bytes)?)}
fn code(cert:&str,token:&str)->String{let hash=util::digest(format!("transfer-pair-v1|{cert}|{token}"));let n=u32::from_str_radix(&hash[..8],16).unwrap_or_default()%1_000_000;format!("{n:06}")}
fn valid_node(id:&str)->bool{id.len()==24&&id.bytes().all(|v|v.is_ascii_hexdigit())}
fn lan(address:SocketAddr)->bool{match address.ip(){IpAddr::V4(ip)=>ip.is_private()||ip.is_loopback()||ip.is_link_local(),IpAddr::V6(ip)=>ip.is_loopback()||ip.is_unique_local()||ip.is_unicast_link_local()}}
fn safe_id(id:&str)->bool{!id.is_empty()&&id.len()<=64&&id.bytes().all(|b|b.is_ascii_alphanumeric()||b"_-".contains(&b))}
fn public(p:&Pending)->Value{json!({"id":p.id,"node_id":p.node_id,"name":p.name,"endpoint":p.endpoint,"code":p.code,"role":p.role,"expires_at":p.created+PAIR_TTL,"requires_local_confirmation":true})}
async fn request(address:SocketAddr,pin:Option<String>,wire:Value,timeout_seconds:u64)->Result<(Value,String)>{
 if !lan(address){bail!("Transfer only permits private or loopback LAN addresses");}
 let client=TlsConnector::from(tls_client_config(pin)?);
 let connect=async{let stream=TcpStream::connect(address).await?;let mut tls=client.connect(ServerName::try_from("endlessvibe.local")?.to_owned(),stream).await?;let cert=tls.get_ref().1.peer_certificates().and_then(|cs|cs.first()).context("Transfer server did not present a certificate")?;let fingerprint=util::digest(cert.as_ref());send(&mut tls,&wire).await?;let answer=recv(&mut tls).await?;Ok::<_,anyhow::Error>((answer,fingerprint))};
 tokio::time::timeout(Duration::from_secs(timeout_seconds),connect).await.context("Transfer peer connection timed out")?
}
impl TransferManager{
 pub fn pending(&self)->Result<Value>{let now=util::now();let items:Vec<Pending>=self.db.transaction(|tx|{let mut q=tx.prepare("SELECT value FROM kv WHERE namespace=?1 AND (expires=0 OR expires>?2) ORDER BY rowid DESC LIMIT 50")?;let rows=q.query_map(rusqlite::params![PENDING,now],|r|r.get::<_,String>(0))?.collect::<rusqlite::Result<Vec<_>>>()?;rows.into_iter().map(|s|Ok(serde_json::from_str(&s)?)).collect()})?;Ok(json!({"pending":items.iter().map(public).collect::<Vec<_>>()}))}
 pub fn peers(&self)->Result<Value>{let items:Vec<Peer>=self.db.transaction(|tx|{let mut q=tx.prepare("SELECT value FROM kv WHERE namespace=?1 ORDER BY rowid DESC LIMIT 50")?;let rows=q.query_map([PAIRS],|r|r.get::<_,String>(0))?.collect::<rusqlite::Result<Vec<_>>>()?;rows.into_iter().map(|s|Ok(serde_json::from_str(&s)?)).collect()})?;let discovered=self.discoveries();Ok(json!({"peers":items.iter().map(|p|{let seen=discovered["peers"].as_array().and_then(|items|items.iter().find(|d|d["node_id"]==p.node_id));json!({"node_id":p.node_id,"name":p.name,"endpoint":p.endpoint,"role":p.role,"paired_at":p.paired_at,"grants":p.grants,"discovery_online":seen.and_then(|v|v["online"].as_bool()).unwrap_or(false),"discovered_last_seen":seen.and_then(|v|v["last_seen"].as_u64())})}).collect::<Vec<_>>()}))}
 pub async fn start_pair(&self,address:SocketAddr)->Result<Value>{if !self.config.enabled{bail!("Transfer is disabled");}if !lan(address){bail!("Pair target must be a private LAN IP address");}let id=util::digest(util::random_secret()?)[..24].to_owned();let token=util::random_secret()?;let hello=json!({"kind":"pair_hello","node_id":self.node_id,"name":self.config.display_name,"id":id,"token":token});let(v,cert_sha)=request(address,None,hello,12).await?;if v["ok"]!=true{bail!("Pair offer refused: {}",v["error"].as_str().unwrap_or("unknown"));}let peer=v["node_id"].as_str().context("Pair response lacked node ID")?;if !valid_node(peer)||peer==self.node_id{bail!("Invalid remote Node ID");}let pairing_code=code(&cert_sha,&token);if v["code"].as_str()!=Some(&pairing_code){bail!("Pair verification code mismatch");}let pending=Pending{id,node_id:peer.into(),name:v["name"].as_str().unwrap_or("Remote").to_owned(),endpoint:address,cert_sha,token_hash:util::digest(&token),token,code:pairing_code,role:"parent".into(),created:util::now()};self.db.put(PENDING,&pending.id,&pending,pending.created+PAIR_TTL)?;Ok(public(&pending))}
 pub fn receive_pair(&self,wire:&Wire,address:SocketAddr,cert_sha:&str)->Result<Value>{if !valid_node(&wire.node_id)||wire.node_id==self.node_id||wire.id.len()!=24||wire.token.len()<32||wire.name.is_empty()||wire.name.len()>64{bail!("Invalid Transfer pair offer");}if let Some(existing)=self.db.get::<String>("transfer_meta","parent_node")?{if existing!=wire.node_id{bail!("This child is already paired with a different parent");}}let item=Pending{id:wire.id.clone(),node_id:wire.node_id.clone(),name:wire.name.clone(),endpoint:address,cert_sha:cert_sha.into(),token_hash:util::digest(&wire.token),token:String::new(),code:code(cert_sha,&wire.token),role:"child".into(),created:util::now()};self.db.put(PENDING,&item.id,&item,item.created+PAIR_TTL)?;Ok(json!({"ok":true,"node_id":self.node_id,"name":self.config.display_name,"code":item.code}))}
 pub fn approve_pair(&self,request:PairApprove,rt:&crate::runtime::Runtime)->Result<Value>{let p:Pending=self.db.get(PENDING,&request.id)?.context("Pair request is missing or expired")?;if util::now().saturating_sub(p.created)>PAIR_TTL{bail!("Pair request expired");}if p.role=="child"{if request.grants.is_empty(){bail!("Child must explicitly grant at least one Project");}if request.grants.len()>32{bail!("Too many Project grants");}for g in &request.grants{if !safe_id(&g.workspace)||!safe_id(&g.project){bail!("Invalid Project grant");}let project=rt.project_exact(&g.workspace,&g.project)?;if (g.write||g.execute||g.git)&&!project.config.allow_write||(g.execute&&!project.config.allow_exec)||(g.git&&!project.config.allow_git_commit){bail!("Grant exceeds the child's existing Project permissions");}}if let Some(existing)=self.db.get::<String>("transfer_meta","parent_node")?{if existing!=p.node_id{bail!("Child already paired with a different parent");}}}
 let peer=Peer{node_id:p.node_id.clone(),name:p.name.clone(),endpoint:p.endpoint,cert_sha:p.cert_sha,role:p.role.clone(),token:p.token,token_hash:p.token_hash,grants:if p.role=="child"{request.grants}else{vec![]},paired_at:util::now()};self.db.transaction(|tx|{if peer.role=="child"{crate::store::put(tx,"transfer_meta","parent_node",&peer.node_id,0)?;}crate::store::put(tx,PAIRS,&peer.node_id,&peer,0)?;crate::store::delete(tx,PENDING,&request.id)?;Ok(())})?;Ok(json!({"paired":true,"node_id":peer.node_id,"role":peer.role,"grants":peer.grants}))}
 pub fn revoke_pair(&self,node_id:&str)->Result<Value>{if !valid_node(node_id){bail!("Invalid Node ID");}self.db.transaction(|tx|{let item:Option<Peer>=crate::store::get(tx,PAIRS,node_id)?;if let Some(ref p)=item{if p.role=="child"{crate::store::delete(tx,"transfer_meta","parent_node")?;}crate::store::delete(tx,PAIRS,node_id)?;}Ok(json!({"revoked":item.is_some(),"node_id":node_id}))})}
 pub fn incoming_peer(&self,node_id:&str,token:&str)->Result<Peer>{let peer:Peer=self.db.get(PAIRS,node_id)?.context("Transfer peer is not paired")?;if peer.role!="child"{bail!("This peer cannot control local Projects");}let hash=util::digest(token);if token.len()<32||!bool::from(subtle::ConstantTimeEq::ct_eq(hash.as_bytes(),peer.token_hash.as_bytes())){bail!("Invalid Transfer peer credential");}Ok(peer)}
 pub async fn call_node(&self,node_id:&str,tool:&str,args:Value)->Result<Value>{if !self.config.enabled{bail!("Transfer is disabled");}if !valid_node(node_id){bail!("Invalid target Node ID");}let peer:Peer=self.db.get(PAIRS,node_id)?.context("Node is not paired")?;if peer.role!="parent"||peer.token.is_empty(){bail!("Only an approved parent may forward Project calls to a child");}let req=json!({"kind":"call","node_id":self.node_id,"token":peer.token,"tool":tool,"args":args});let(answer,fingerprint)=request(peer.endpoint,Some(peer.cert_sha.clone()),req,90).await?;if fingerprint!=peer.cert_sha{bail!("Transfer child certificate changed");}if answer["ok"]!=true{bail!("Child refused transfer request: {}",answer["error"].as_str().unwrap_or("unknown"));}Ok(answer["result"].clone())}
 pub fn authorized(&self,node_id:&str,token:&str,workspace:&str,project:&str,operation:&str)->Result<Grant>{let peer=self.incoming_peer(node_id,token)?;let grant=peer.grants.into_iter().find(|g|g.workspace==workspace&&g.project==project).context("Project not granted to parent")?;let allowed=match operation{"read"=>grant.read,"write"=>grant.write,"execute"=>grant.execute,"git"=>grant.git,_=>false};if !allowed{bail!("Transfer operation not granted");}Ok(grant)}
 pub async fn run_tls(self:Arc<Self>,shutdown:CancellationToken,rt:Option<Arc<crate::runtime::Runtime>>)->Result<()>{let server=tls_server_config(&self.db)?;let listener=TcpListener::bind(self.config.listen).await.with_context(||format!("Cannot bind Transfer TLS {}",self.config.listen))?;let acceptor=TlsAcceptor::from(server);let slots=Arc::new(tokio::sync::Semaphore::new(12));loop{tokio::select!{_ = shutdown.cancelled()=>break,connection=listener.accept()=>{let(stream,addr)=connection?;if !lan(addr){continue;}let Ok(permit)=slots.clone().try_acquire_owned()else{continue;};let manager=self.clone();let tls=acceptor.clone();let rt=rt.clone();tokio::spawn(async move{let _permit=permit;let fut=async{let mut session=tls.accept(stream).await?;let request=recv(&mut session).await?;let wire:Wire=serde_json::from_value(request)?;let cert:Vec<u8>=manager.db.get::<(Vec<u8>,Vec<u8>)>("transfer_meta","tls_identity")?.context("Missing server identity")?.0;let digest=util::digest(&cert);let response=match wire.kind.as_str(){"pair_hello"=>manager.receive_pair(&wire,addr,&digest),"call"=>{let rt=rt.context("Transfer Project routing is not active")?;crate::transfer::router::dispatch(rt,manager.clone(),wire).await.map(|outcome|json!({"ok":true,"node_id":manager.node_id,"result":outcome}))},_=>Err(anyhow::anyhow!("Transfer request type is not supported"))};let data=match response{Ok(value)=>value,Err(e)=>json!({"ok":false,"error":util::bounded_text(&e.to_string(),200)})};send(&mut session,&data).await?;Ok::<_,anyhow::Error>(())};if let Err(error)=tokio::time::timeout(Duration::from_secs(95),fut).await.unwrap_or_else(|_|Err(anyhow::anyhow!("Peer request timed out"))){tracing::debug!(error=%error,"Transfer TLS session failed");}});}}}Ok(())}
}
#[cfg(test)]mod tests{use super::*;
#[tokio::test]async fn tls_pair_offer_matches_both_nodes_and_never_grants_projects(){let a=tempfile::tempdir().unwrap();let b=tempfile::tempdir().unwrap();let db_a=Arc::new(Store::open(&a.path().join("state")).unwrap());let db_b=Arc::new(Store::open(&b.path().join("state")).unwrap());let listener=TcpListener::bind("127.0.0.1:0").await.unwrap();let address=listener.local_addr().unwrap();drop(listener);let mut child_cfg=crate::config::Transfer::default();child_cfg.enabled=true;child_cfg.listen=address;child_cfg.display_name="Child".into();let child=TransferManager::new(child_cfg,db_b).unwrap();let mut parent_cfg=crate::config::Transfer::default();parent_cfg.enabled=true;let parent=TransferManager::new(parent_cfg,db_a).unwrap();let shutdown=CancellationToken::new();let task=tokio::spawn(child.clone().run_tls(shutdown.clone(),None));tokio::time::sleep(Duration::from_millis(100)).await;let result=parent.start_pair(address).await.unwrap();assert_eq!(result["role"],"parent");let pending=child.pending().unwrap();assert_eq!(pending["pending"][0]["code"],result["code"]);assert_eq!(pending["pending"][0]["node_id"],parent.node_id);assert_eq!(child.peers().unwrap()["peers"].as_array().unwrap().len(),0);assert!(child.authorized(&parent.node_id,"invalid","w","p","read").is_err());shutdown.cancel();task.await.unwrap().unwrap();}
#[test]fn code_is_stable_and_permissions_fail_closed(){assert_eq!(code("cert","token"),code("cert","token"));assert_ne!(code("cert","token"),code("cert2","token"));assert!(!lan("8.8.8.8:20002".parse().unwrap()));assert!(lan("127.0.0.1:20002".parse().unwrap()));}}
