//! Single-owner OAuth authorization-code + S256 PKCE server and resource-server checks.
//! Tokens/codes are random 256-bit opaque values; only their hashes are stored.
//! No token-in-query authentication, no anonymous private tools, no password grant.
use crate::{config::Config, runtime::Runtime, store::{self, Store}, util};
use anyhow::{bail, Result};
use axum::{body::{to_bytes, Body}, extract::{Request, State}, http::{header, HeaderMap, HeaderValue, StatusCode}, middleware::Next, response::{Html, IntoResponse, Redirect, Response}, Form, Json};
use base64::{engine::general_purpose::{STANDARD, URL_SAFE_NO_PAD}, Engine};
use rusqlite::Transaction;
use rmcp::model::{ClientJsonRpcMessage,ClientNotification,ClientRequest,JsonRpcRequest,RequestId};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::{collections::HashMap, sync::{Arc, Mutex}, time::{Duration, Instant}};
use url::Url;

mod policy;
mod scopes;
pub use policy::valid_redirect;
pub use scopes::required_scopes;
use policy::pkce_verifier;
use scopes::{parse as scopes,SCOPES};
pub struct Auth { pub db: Arc<Store>, pub config: Arc<Config>, owner_hash: String, rate: Mutex<HashMap<&'static str, (Instant, u32)>> }
#[derive(Clone, Debug)] pub struct Principal { pub client_id: String, pub scopes: Vec<String> }
#[derive(Clone, Serialize, Deserialize)] struct Client { id: String, name: String, redirects: Vec<String>, method: String, secret_hash: Option<String> }
#[derive(Clone, Serialize, Deserialize)] struct Grant { client_id: String, redirect_uri: String, state: String, challenge: String, resource: String, scopes: Vec<String>, csrf_hash: String, expires: u64 }
#[derive(Clone, Serialize, Deserialize)] struct Code { grant: Grant }
#[derive(Clone, Serialize, Deserialize)] struct Token { client_id: String, family: String, kind: String, resource: String, scopes: Vec<String>, expires: u64, used: bool }
#[derive(Debug)] pub struct AuthError { status: StatusCode, code: &'static str, description: String }
type AResult<T> = std::result::Result<T, AuthError>;
impl AuthError { fn bad(code: &'static str, description: &str) -> Self { Self { status: StatusCode::BAD_REQUEST, code, description: description.into() } } }
impl From<anyhow::Error> for AuthError { fn from(e: anyhow::Error) -> Self { tracing::error!(error=%e,"Authentication operation failed"); Self { status: StatusCode::INTERNAL_SERVER_ERROR, code: "server_error", description: "Authentication storage error; inspect local logs".into() } } }
impl IntoResponse for AuthError { fn into_response(self) -> Response { /* Descriptions are fixed server messages, never request values. */ tracing::warn!(oauth_error=self.code,reason=%self.description,status=self.status.as_u16(),"OAuth request rejected");(self.status, Json(json!({"error":self.code,"error_description":self.description}))).into_response() } }

impl Auth {
    pub fn new(config: Arc<Config>, db: Arc<Store>) -> Result<Self> {
        let key = String::from_utf8(util::private_read(&config.security.data_dir.join("owner.key"), 256)?)?;
        let key = key.trim(); if key.len() != 43 || URL_SAFE_NO_PAD.decode(key)?.len() != 32 { bail!("owner.key must be generated by --init or --rotate-owner-key"); }
        Ok(Self { config, db, owner_hash: util::digest(key), rate: Mutex::new(HashMap::new()) })
    }
    fn rate(&self, key: &'static str, limit: u32) -> AResult<()> {
        let mut rates = self.rate.lock().map_err(|_|AuthError::bad("server_error","Rate limiter unavailable"))?;
        let (start, count) = rates.entry(key).or_insert((Instant::now(), 0));
        if start.elapsed() > Duration::from_secs(60) { *start = Instant::now(); *count = 0; }
        *count += 1; if *count > limit { return Err(AuthError { status: StatusCode::TOO_MANY_REQUESTS, code: "temporarily_unavailable", description: "Authorization rate limit; retry in one minute".into() }); } Ok(())
    }
    pub fn metadata(&self) -> Value { json!({"issuer":self.config.server.public_url,"authorization_endpoint":format!("{}/oauth/authorize",self.config.server.public_url),"token_endpoint":format!("{}/oauth/token",self.config.server.public_url),"registration_endpoint":format!("{}/oauth/register",self.config.server.public_url),"revocation_endpoint":format!("{}/oauth/revoke",self.config.server.public_url),"response_types_supported":["code"],"grant_types_supported":["authorization_code","refresh_token"],"token_endpoint_auth_methods_supported":["none","client_secret_post","client_secret_basic"],"code_challenge_methods_supported":["S256"],"authorization_response_iss_parameter_supported":true,"scopes_supported":SCOPES}) }
    pub fn resource_metadata(&self) -> Value { json!({"resource":self.config.resource(),"authorization_servers":[self.config.server.public_url],"scopes_supported":SCOPES,"bearer_methods_supported":["header"]}) }
    pub fn challenge(&self, error: Option<&str>, scopes: &[&str]) -> HeaderValue {
        let mut s = format!("Bearer resource_metadata=\"{}/.well-known/oauth-protected-resource\"", self.config.server.public_url);
        if let Some(e) = error { let description=if e=="insufficient_scope"{"Reconnect EndlessVibe to grant the required permissions"}else{"Connect EndlessVibe with OAuth; the access token is missing, invalid or expired"};s.push_str(&format!(", error=\"{e}\", error_description=\"{description}\"")); }
        if !scopes.is_empty() { s.push_str(&format!(", scope=\"{}\"",scopes.join(" "))); }
        HeaderValue::from_str(&s).unwrap_or_else(|_| HeaderValue::from_static("Bearer"))
    }
    pub fn authenticate(&self, headers: &HeaderMap) -> Result<Principal> {
        let value = headers.get(header::AUTHORIZATION).and_then(|v|v.to_str().ok()).unwrap_or("");
        let (scheme, raw) = value.split_once(' ').unwrap_or(("", ""));
        if !scheme.eq_ignore_ascii_case("bearer") || raw.len() != 43 { bail!("Bearer token required"); }
        let t: Token = self.db.get("tokens", &util::digest(raw))?.ok_or_else(||anyhow::anyhow!("Token invalid or expired"))?;
        if t.kind != "access" || t.used || t.expires <= util::now() || t.resource != self.config.resource() { bail!("Token invalid or expired"); }
        Ok(Principal { client_id: t.client_id, scopes: t.scopes })
    }
    pub fn issue_local_token(&self) -> Result<String> {
        let raw = util::random_secret()?;
        let t = Token { client_id: "local-admin".into(), family: util::random_secret()?, kind:"access".into(), resource:self.config.resource(), scopes:SCOPES.iter().map(|s|(*s).into()).collect(),expires:util::now()+self.config.security.access_token_seconds,used:false };
        self.db.put("tokens", &util::digest(&raw), &t, t.expires)?; Ok(raw)
    }
    pub fn revoke_all(&self) -> Result<()> { self.db.transaction(|tx| { tx.execute("DELETE FROM kv WHERE namespace IN ('tokens','codes','grants')",[])?; Ok(()) }) }
}

fn cookie(headers: &HeaderMap, name: &str) -> Option<String> { headers.get(header::COOKIE)?.to_str().ok()?.split(';').find_map(|p|p.trim().split_once('=').filter(|(k,_)|*k == name).map(|(_,v)|v.to_owned())) }
fn check_browser_origin(headers: &HeaderMap, public_url: &str) -> AResult<()> {
    let origin=Url::parse(public_url).map_err(|_|AuthError::bad("server_error","Invalid configured public origin"))?.origin().ascii_serialization();
    if let Some(value)=headers.get(header::ORIGIN){
        if value.to_str().ok()!=Some(origin.as_str()){
            let origin_check=if value.to_str().ok()==Some("null"){"opaque"}else{"mismatch"};
            tracing::warn!(origin_check,"Consent origin check failed");
            return Err(AuthError::bad("invalid_request","Cross-origin consent POST refused"));
        }
    }
    Ok(())
}

pub async fn oauth_metadata(State(rt): State<Arc<Runtime>>) -> Json<Value> { Json(rt.auth.metadata()) }
pub async fn protected_metadata(State(rt): State<Arc<Runtime>>) -> Json<Value> { Json(rt.auth.resource_metadata()) }
#[derive(Deserialize)] pub struct Register { redirect_uris: Vec<String>, client_name: Option<String>, token_endpoint_auth_method: Option<String>, grant_types: Option<Vec<String>>, response_types: Option<Vec<String>> }
pub async fn register(State(rt): State<Arc<Runtime>>, Json(body): Json<Register>) -> AResult<Response> {
    rt.auth.rate("register",20)?; rt.db.prune_auth()?;
    if body.redirect_uris.is_empty() || body.redirect_uris.len() > 8 || body.redirect_uris.iter().any(|u|!valid_redirect(&rt.config,u)) { return Err(AuthError::bad("invalid_redirect_uri","Use an exact approved ChatGPT callback; add Inspector callbacks explicitly in config")); }
    if body.grant_types.as_ref().is_some_and(|g|g.iter().any(|v| !matches!(v.as_str(),"authorization_code"|"refresh_token"))) || body.response_types.as_ref().is_some_and(|r|r.iter().any(|v|v != "code")) { return Err(AuthError::bad("invalid_client_metadata","Unsupported OAuth grant or response type")); }
    let method = body.token_endpoint_auth_method.unwrap_or_else(||"none".into());
    if !matches!(method.as_str(),"none"|"client_secret_post"|"client_secret_basic") { return Err(AuthError::bad("invalid_client_metadata","Unsupported token endpoint authentication method")); }
    let secret = if method == "none" { None } else { Some(util::random_secret()?) };
    let c = Client { id:format!("ev_{}",util::random_secret()?), name:util::bounded_text(body.client_name.as_deref().unwrap_or("MCP client"),128), redirects:body.redirect_uris,method,secret_hash:secret.as_ref().map(util::digest) };
    rt.db.transaction(|tx| { if store::count(tx,"clients")? >= 1024 { bail!("OAuth client capacity reached"); } store::put(tx,"clients",&c.id,&c,0) })?;
    let mut result = json!({"client_id":c.id,"client_id_issued_at":util::now(),"client_name":c.name,"redirect_uris":c.redirects,"token_endpoint_auth_method":c.method,"grant_types":["authorization_code","refresh_token"],"response_types":["code"]});
    if let Some(secret) = secret { result["client_secret"] = json!(secret); result["client_secret_expires_at"] = json!(0); }
    Ok((StatusCode::CREATED,Json(result)).into_response())
}
#[derive(Deserialize)] pub struct Authorize { client_id:String,redirect_uri:String,response_type:String,state:String,code_challenge:String,code_challenge_method:String,resource:String,scope:Option<String> }
pub async fn authorize(State(rt): State<Arc<Runtime>>, axum::extract::Query(q): axum::extract::Query<Authorize>) -> AResult<Response> {
    rt.auth.rate("authorize",30)?; rt.db.prune_auth()?;
    let c: Client = rt.db.get("clients",&q.client_id)?.ok_or_else(||AuthError::bad("invalid_client","Unknown OAuth client"))?;
    if !c.redirects.contains(&q.redirect_uri) || !valid_redirect(&rt.config,&q.redirect_uri) { return Err(AuthError::bad("invalid_redirect_uri","Unregistered redirect URI")); }
    if q.response_type != "code" || q.code_challenge_method != "S256" || q.code_challenge.len() != 43 || URL_SAFE_NO_PAD.decode(&q.code_challenge).map_or(true,|v|v.len()!=32) || q.resource != rt.config.resource() || q.state.is_empty() || q.state.len()>2048 { return Err(AuthError::bad("invalid_request","Require code, S256 PKCE, state and the exact resource URL")); }
    let grant = Grant { client_id:c.id,redirect_uri:q.redirect_uri,state:q.state,challenge:q.code_challenge,resource:q.resource,scopes:scopes(q.scope.as_deref())?,csrf_hash:String::new(),expires:util::now()+300 };
    let nonce = util::random_secret()?; let id = util::random_secret()?;
    let grant = Grant { csrf_hash:util::digest(&nonce),..grant }; rt.db.put("grants",&id,&grant,grant.expires)?;
    let permissions = grant.scopes.iter().map(|s|format!("<li><code>{}</code></li>",util::html(s))).collect::<String>();
    let body = format!(r#"<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EndlessVibe · 授权</title><link rel="icon" type="image/png" href="/assets/EndlessVibe.png"><link rel="stylesheet" href="/assets/app.css"></head><body><main class="shell"><div class="oauth-brand"><img class="brand-icon oauth-icon" src="/assets/EndlessVibe.png" width="90" height="60" alt=""><h1>授权访问 EndlessVibe</h1></div><section class="overview"><p>客户端：<strong>{}</strong></p><p>将允许此客户端操作管理员配置的项目。代码、文件内容和命令输出会返回客户端。执行命令可能修改项目，请先核对权限。</p><ul>{}</ul><p>回调：<code>{}</code></p><form method="post" action="/oauth/authorize"><input type="hidden" name="transaction" value="{}"><label>管理员密钥（本机初始化生成的 owner.key）<input type="password" name="owner_key" autocomplete="off" maxlength="256" required></label><p>只在你自己的此网页中输入，不要发到聊天、日志或 URL。</p><button type="submit" name="decision" value="approve">授权</button><button type="submit" name="decision" value="deny" formnovalidate>拒绝</button></form></section></main></body></html>"#,util::html(&c.name),permissions,util::html(&grant.redirect_uri),util::html(&id));
    let mut response = Html(body).into_response();
    // no-referrer can turn a browser's same-origin form POST Origin into null.
    // same-origin preserves consent validation and omits referrers to ChatGPT.
    response.headers_mut().insert(header::REFERRER_POLICY,HeaderValue::from_static("same-origin"));
    let secure = if rt.config.server.public_url.starts_with("https:") { "; Secure" } else { "" };
    response.headers_mut().insert(header::SET_COOKIE,HeaderValue::from_str(&format!("ev_consent={nonce}; Path=/oauth; HttpOnly; SameSite=Lax; Max-Age=300{secure}")).unwrap());
    Ok(response)
}
#[derive(Deserialize)] pub struct Consent { transaction:String, #[serde(default)] owner_key:String, decision:String }
pub async fn consent(State(rt): State<Arc<Runtime>>, headers: HeaderMap, Form(form): Form<Consent>) -> AResult<Response> {
    rt.auth.rate("consent",20)?; check_browser_origin(&headers,&rt.config.server.public_url)?;
    let grant: Grant = rt.db.get("grants",&form.transaction)?.ok_or_else(||AuthError::bad("invalid_request","Consent expired; restart linking"))?;
    let nonce = cookie(&headers,"ev_consent").unwrap_or_default();
    if nonce.len() != 43 || !util::constant_eq(&util::digest(nonce),&grant.csrf_hash) || grant.expires <= util::now() { return Err(AuthError::bad("invalid_request","Consent cookie invalid; restart linking")); }
    let approve = form.decision == "approve";
    if form.decision != "deny" && !approve { return Err(AuthError::bad("invalid_request","Unknown consent decision")); }
    if approve && !util::constant_eq(&util::digest(form.owner_key.trim()),&rt.auth.owner_hash) { return Err(AuthError { status:StatusCode::FORBIDDEN,code:"access_denied",description:"Administrator key is incorrect".into() }); }
    let code = util::random_secret()?;
    let consumed = rt.db.transaction(|tx| { if store::get::<Grant>(tx,"grants",&form.transaction)?.is_none() { return Ok(false); } store::delete(tx,"grants",&form.transaction)?; if approve { store::put(tx,"codes",&util::digest(&code),&Code { grant:grant.clone() },util::now()+120)?; } Ok(true) })?;
    if !consumed { return Err(AuthError::bad("invalid_request","Consent already consumed")); }
    let mut redirect = Url::parse(&grant.redirect_uri).map_err(|_|AuthError::bad("invalid_redirect_uri","Invalid stored redirect"))?;
    { let mut query = redirect.query_pairs_mut(); if approve { query.append_pair("code",&code); } else { query.append_pair("error","access_denied"); } query.append_pair("state",&grant.state).append_pair("iss",&rt.config.server.public_url); }
    let mut result = Redirect::to(redirect.as_str()).into_response();
    let secure = if rt.config.server.public_url.starts_with("https:") { "; Secure" } else { "" };
    result.headers_mut().insert(header::SET_COOKIE,HeaderValue::from_str(&format!("ev_consent=; Path=/oauth; HttpOnly; SameSite=Lax; Max-Age=0{secure}")).unwrap());
    rt.db.audit("oauth_consent","",if approve {"approved"} else {"denied"},&grant.client_id)?; Ok(result)
}

#[derive(Deserialize)] pub struct TokenRequest { grant_type:String,client_id:Option<String>,client_secret:Option<String>,code:Option<String>,code_verifier:Option<String>,redirect_uri:Option<String>,refresh_token:Option<String>,resource:Option<String>,scope:Option<String> }
fn identify(auth: &Auth, headers: &HeaderMap, id: Option<&str>, secret: Option<&str>) -> AResult<Client> {
    let mut given_id = id.map(str::to_owned); let mut given_secret = secret.map(str::to_owned); let mut method = if secret.is_some() { "client_secret_post" } else { "none" };
    if let Some(h) = headers.get(header::AUTHORIZATION) {
        let h = h.to_str().map_err(|_|AuthError::bad("invalid_client","Bad client authorization"))?;
        let (scheme,data) = h.split_once(' ').ok_or_else(||AuthError::bad("invalid_client","Bad client authorization"))?;
        if !scheme.eq_ignore_ascii_case("basic") || secret.is_some() { return Err(AuthError::bad("invalid_client","Conflicting client authentication")); }
        let pair = String::from_utf8(STANDARD.decode(data).map_err(|_|AuthError::bad("invalid_client","Bad Basic authentication"))?).map_err(|_|AuthError::bad("invalid_client","Bad Basic authentication"))?;
        let (cid,cs) = pair.split_once(':').ok_or_else(||AuthError::bad("invalid_client","Bad Basic authentication"))?;
        if id.is_some_and(|v|v != cid) { return Err(AuthError::bad("invalid_client","Client mismatch")); }
        given_id = Some(cid.into()); given_secret = Some(cs.into()); method = "client_secret_basic";
    }
    let id = given_id.ok_or_else(||AuthError::bad("invalid_client","client_id is required"))?;
    let c: Client = auth.db.get("clients",&id)?.ok_or_else(||AuthError::bad("invalid_client","Unknown OAuth client"))?;
    if c.method != method || c.secret_hash.as_ref().is_some_and(|hash| !util::constant_eq(hash,&util::digest(given_secret.as_deref().unwrap_or("")))) { return Err(AuthError::bad("invalid_client","Client authentication failed")); } Ok(c)
}
fn pair(tx: &Transaction<'_>, auth: &Auth, client_id: &str, scopes: Vec<String>, family: String) -> Result<Value> {
    let access = util::random_secret()?; let refresh = util::random_secret()?; let now = util::now();
    let a = Token { client_id:client_id.into(),family,kind:"access".into(),resource:auth.config.resource(),scopes,expires:now+auth.config.security.access_token_seconds,used:false };
    let r = Token { kind:"refresh".into(),expires:now+auth.config.security.refresh_token_seconds,..a.clone() };
    store::put(tx,"tokens",&util::digest(&access),&a,a.expires)?; store::put(tx,"tokens",&util::digest(&refresh),&r,r.expires)?;
    Ok(json!({"access_token":access,"refresh_token":refresh,"token_type":"Bearer","expires_in":auth.config.security.access_token_seconds,"scope":a.scopes.join(" ")}))
}
pub async fn token(State(rt): State<Arc<Runtime>>, headers: HeaderMap, Form(p): Form<TokenRequest>) -> AResult<Json<Value>> {
    rt.auth.rate("token",120)?; rt.db.prune_auth()?;
    let c = identify(&rt.auth,&headers,p.client_id.as_deref(),p.client_secret.as_deref())?;
    if p.resource.as_deref() != Some(rt.config.resource().as_str()) { return Err(AuthError::bad("invalid_target","resource must exactly match the protected resource")); }
    let result = match p.grant_type.as_str() {
        "authorization_code" => {
            let raw = p.code.as_deref().ok_or_else(||AuthError::bad("invalid_grant","code is required"))?;
            let verifier = p.code_verifier.as_deref().unwrap_or("");
            if !pkce_verifier(verifier) { return Err(AuthError::bad("invalid_grant","A valid PKCE verifier is required")); }
            let challenge = URL_SAFE_NO_PAD.encode(Sha256::digest(verifier.as_bytes()));
            rt.db.transaction(|tx| {
                let Some(code) = store::get::<Code>(tx,"codes",&util::digest(raw))? else { return Ok(None) };
                if code.grant.client_id != c.id || p.redirect_uri.as_deref() != Some(code.grant.redirect_uri.as_str()) || code.grant.resource != rt.config.resource() || !util::constant_eq(&challenge,&code.grant.challenge) { return Ok(None); }
                store::delete(tx,"codes",&util::digest(raw))?;
                Ok(Some(pair(tx,&rt.auth,&c.id,code.grant.scopes,util::random_secret()?)?))
            })?
        }
        "refresh_token" => {
            let raw = p.refresh_token.as_deref().ok_or_else(||AuthError::bad("invalid_grant","refresh_token is required"))?;
            let requested = p.scope.as_deref().map(|s|scopes(Some(s))).transpose()?;
            rt.db.transaction(|tx| {
                let Some(mut r) = store::get::<Token>(tx,"tokens",&util::digest(raw))? else { return Ok(None) };
                if r.kind != "refresh" || r.client_id != c.id || r.resource != rt.config.resource() || r.expires<=util::now() { return Ok(None); }
                if r.used { tx.execute("DELETE FROM kv WHERE namespace='tokens' AND json_extract(value,'$.family')=?1",[&r.family])?; return Ok(None); } // Commit family revocation, even though the HTTP response is an error.
                let scope = requested.clone().unwrap_or_else(||r.scopes.clone()); if scope.iter().any(|s|!r.scopes.contains(s)) { return Ok(None); }
                r.used = true; store::put(tx,"tokens",&util::digest(raw),&r,r.expires)?;
                Ok(Some(pair(tx,&rt.auth,&c.id,scope,r.family)?))
            })?
        }
        _ => return Err(AuthError::bad("unsupported_grant_type","Only authorization_code and refresh_token are supported")),
    };
    result.map(Json).ok_or_else(||AuthError::bad("invalid_grant","Code/token invalid, expired, replayed, or bound to different parameters"))
}
#[derive(Deserialize)] pub struct Revoke { client_id:Option<String>,client_secret:Option<String>,token:String }
pub async fn revoke(State(rt): State<Arc<Runtime>>, headers: HeaderMap, Form(p): Form<Revoke>) -> AResult<StatusCode> {
    rt.auth.rate("token",120)?; let c = identify(&rt.auth,&headers,p.client_id.as_deref(),p.client_secret.as_deref())?;
    rt.db.transaction(|tx| { if let Some(t) = store::get::<Token>(tx,"tokens",&util::digest(&p.token))? { if t.client_id == c.id { tx.execute("DELETE FROM kv WHERE namespace='tokens' AND json_extract(value,'$.family')=?1",[t.family])?; } } Ok(()) })?;
    Ok(StatusCode::OK)
}

fn unauthorized(auth:&Auth,has_credentials:bool)->Response{
    let mut response=(StatusCode::UNAUTHORIZED,Json(json!({"error":"unauthorized","message":"OAuth authorization is required"}))).into_response();
    response.headers_mut().insert(header::WWW_AUTHENTICATE,auth.challenge(has_credentials.then_some("invalid_token"),SCOPES));response
}
fn tool_auth_error(auth:&Auth,id:&RequestId,error:&str,needed:&[&str])->Response{
    tracing::info!(oauth_error=error,"MCP tool requires OAuth linking");
    let scope=if needed.is_empty(){SCOPES}else{needed};
    let challenge=auth.challenge(Some(error),scope);
    let description=if error=="insufficient_scope"{"Reconnect EndlessVibe to grant the required permissions."}else{"Connect EndlessVibe with OAuth before using this tool."};
    // This is a failed tool result, not successful execution. HTTP 200 lets the
    // host read mcp/www_authenticate and launch its tool-level OAuth linking UI.
    let mut response=Json(json!({"jsonrpc":"2.0","id":id,"result":{"isError":true,"content":[{"type":"text","text":description}],"_meta":{"mcp/www_authenticate":[challenge.to_str().unwrap_or("Bearer")]}}})).into_response();
    response.headers_mut().insert(header::WWW_AUTHENTICATE,challenge);response
}
pub async fn protect(State(rt): State<Arc<Runtime>>, mut request: Request, next: Next) -> Response {
    let has_credentials=request.headers().contains_key(header::AUTHORIZATION);
    let principal=rt.auth.authenticate(request.headers()).ok();
    if request.method()!=axum::http::Method::POST{
        if let Some(principal)=principal{request.extensions_mut().insert(principal);return next.run(request).await;}
        return unauthorized(&rt.auth,has_credentials);
    }
    let (parts,body)=request.into_parts();
    let bytes=match tokio::time::timeout(Duration::from_secs(15),to_bytes(body,rt.body_limit())).await { Ok(Ok(v))=>v,Ok(Err(_))=>return StatusCode::PAYLOAD_TOO_LARGE.into_response(),Err(_)=>return StatusCode::REQUEST_TIMEOUT.into_response() };
    // Use the SDK's parser so our auth classification matches its dispatch. A
    // batch, malformed call, or forged metadata cannot become a discovery call.
    let message=serde_json::from_slice::<ClientJsonRpcMessage>(&bytes).ok();
    let method=match &message{
        Some(ClientJsonRpcMessage::Request(r))=>match &r.request{
            ClientRequest::InitializeRequest(_)=>"initialize",ClientRequest::ListToolsRequest(_)=>"tools/list",ClientRequest::PingRequest(_)=>"ping",ClientRequest::CallToolRequest(_)=>"tools/call",_=>"other",
        },
        Some(ClientJsonRpcMessage::Notification(n)) if matches!(n.notification,ClientNotification::InitializedNotification(_))=>"notifications/initialized",
        _=>"other",
    };
    let authentication=if principal.is_some(){"valid"}else if has_credentials{"invalid"}else{"missing"};
    tracing::info!(mcp_method=method,authentication,"MCP request");
    if let Some(ClientJsonRpcMessage::Request(JsonRpcRequest{id,request:ClientRequest::CallToolRequest(call),..}))=&message{
        let needed=required_scopes(&call.params.name);
        let Some(principal)=&principal else{return tool_auth_error(&rt.auth,id,"invalid_token",needed);};
        if needed.iter().any(|s|!principal.scopes.iter().any(|v|v.as_str()==*s)){return tool_auth_error(&rt.auth,id,"insufficient_scope",needed);}
    }else if principal.is_none()&&!matches!(method,"initialize"|"notifications/initialized"|"ping"|"tools/list"){
        return unauthorized(&rt.auth,has_credentials);
    }
    // Only static protocol/tool discovery is public. Every tool (including
    // hello and status) passes the token and scope checks above before dispatch.
    request=Request::from_parts(parts,Body::from(bytes));
    if let Some(principal)=principal{request.extensions_mut().insert(principal);}
    let response=next.run(request).await;
    if method=="tools/list"{crate::server::tool_descriptors(response,rt.body_limit()).await}else{response}
}
