use crate::{config::Config,config_edit::{self,AddProjectRequest,UpdateProjectRequest,UpdateReadonlyMountsRequest},security::auth::Auth,store::Store,tools::{jobs::Jobs,process,tasks},util,workspace::{self,Project,Workspace}};
use anyhow::{bail,Context,Result};
use serde_json::{json,Value};
use std::{collections::BTreeMap,fs::File,future::Future,path::{Path,PathBuf},sync::{Arc,Mutex,RwLock,atomic::{AtomicU64,Ordering}},time::Instant};
use tokio::sync::broadcast;
use tokio_util::sync::CancellationToken;

pub struct OperationTrace{pub id:Option<i64>,pub started:Instant,pub tool:String,pub workspace:String,pub project:String,pub task_id:Option<String>,pub stage:Option<String>}
fn service_config_revision(config:&Config)->Result<String>{Ok(util::digest(serde_json::to_vec(&(&config.server,&config.security,&config.limits,&config.execution,&config.git))?))}
fn reuse_project_locks(next:&mut BTreeMap<String,Arc<Workspace>>,old:&BTreeMap<String,Arc<Workspace>>){for(workspace_id,next_workspace)in next.iter_mut(){let Some(old_workspace)=old.get(workspace_id)else{continue};let Some(next_workspace)=Arc::get_mut(next_workspace)else{continue};for(project_id,next_project)in next_workspace.projects.iter_mut(){let Some(old_project)=old_workspace.projects.get(project_id)else{continue};if old_project.root.path!=next_project.root.path{continue;}if let Some(next_project)=Arc::get_mut(next_project){next_project.lock=old_project.lock.clone();}}}}
pub struct Runtime{pub config:Arc<Config>,pub db:Arc<Store>,pub auth:Arc<Auth>,pub jobs:Arc<Jobs>,pub workspaces:RwLock<BTreeMap<String,Arc<Workspace>>>,pub shutdown:CancellationToken,pub config_path:PathBuf,active_config_revision:RwLock<String>,active_service_revision:String,retired_projects:Mutex<Vec<Arc<Project>>>,dashboard_events:broadcast::Sender<String>,config_edit_lock:Mutex<()>,traffic_requests:AtomicU64,traffic_rx:AtomicU64,traffic_tx:AtomicU64,started:Instant,started_unix:u64,_instance:File}
impl Runtime{
    pub fn new(mut config:Config,config_path:&Path)->Result<Arc<Self>>{
        config.validate()?;util::private_dir(&config.security.data_dir)?;config.security.data_dir=config.security.data_dir.canonicalize()?;
        let instance=util::single_instance(&config.security.data_dir.join("service.lock"))?;
        for sub in ["tmp","backups","git-journal","empty-home","exec-cache"]{util::private_dir(&config.security.data_dir.join(sub))?;}
        let cfg=config_path.canonicalize().unwrap_or_else(|_|config_path.to_owned());
        for mount in &config.execution.readonly_mounts{let source=mount.source.canonicalize()?;if config.security.data_dir.starts_with(&source)||source.starts_with(&config.security.data_dir)||cfg.starts_with(&source){bail!("Sandbox mounts must not expose EndlessVibe config, credentials or state");}}
        let workspaces=workspace::load(&config,config_path)?;let active_config_revision=config_edit::revision(config_path).unwrap_or_default();let persisted=if config_path.exists(){Config::load_file(config_path)?}else{config.clone()};let active_service_revision=service_config_revision(&persisted)?;let config_path=config_path.to_owned();let config=Arc::new(config);let db=Arc::new(Store::open(&config.security.data_dir.join("state.sqlite3"))?);let auth=Arc::new(Auth::new(config.clone(),db.clone())?);let jobs=Jobs::new(db.clone(),config.clone())?;let(dashboard_events,_)=broadcast::channel(256);
        Ok(Arc::new(Self{config,db,auth,jobs,workspaces:RwLock::new(workspaces),shutdown:CancellationToken::new(),config_path,active_config_revision:RwLock::new(active_config_revision),active_service_revision,retired_projects:Mutex::new(vec![]),dashboard_events,config_edit_lock:Mutex::new(()),traffic_requests:AtomicU64::new(0),traffic_rx:AtomicU64::new(0),traffic_tx:AtomicU64::new(0),started:Instant::now(),started_unix:util::now(),_instance:instance}))
    }
    fn workspaces_snapshot(&self)->BTreeMap<String,Arc<Workspace>>{self.workspaces.read().unwrap_or_else(|e|e.into_inner()).clone()}
    pub fn projects_snapshot(&self)->Vec<(String,Arc<Project>)>{self.workspaces_snapshot().values().flat_map(|workspace|workspace.projects.values().map(|project|(workspace.config.id.clone(),project.clone()))).collect()}
    pub fn workspace_root_exact(&self,id:&str)->Result<Arc<Workspace>>{self.workspaces.read().unwrap_or_else(|e|e.into_inner()).get(id).cloned().ok_or_else(||crate::error::coded_details("WORKSPACE_NOT_AUTHORIZED",false,"call list_workspaces and use an exact configured workspace ID",json!({"workspace":id})))}
    pub fn workspace_root(&self,id:&str)->Result<Arc<Workspace>>{
        if !id.is_empty() {
            return self.workspace_root_exact(id);
        }

        let single={let workspaces=self.workspaces.read().unwrap_or_else(|e|e.into_inner());if workspaces.len()==1{workspaces.keys().next().cloned()}else{None}};
        if let Some(workspace_id)=single{return self.workspace_root_exact(&workspace_id);}

        self.workspace_root_exact(id)
    }
    pub fn project_exact(&self,workspace:&str,project:&str)->Result<Arc<Project>>{self.workspace_root(workspace)?.project(project)}
    pub fn project(&self,workspace:&str,project:&str)->Result<Arc<Project>>{
        if !project.is_empty() {
            return self.project_exact(workspace, project);
        }

        // Cached pre-refactor ChatGPT tool schemas sent the project ID
        // through the old `workspace` field and had no `project` property.
        let legacy_project = workspace;
        let mut resolved = None;

        for(workspace_id,workspace)in self.workspaces_snapshot(){
            if workspace.project(legacy_project).is_ok(){if resolved.is_some(){return Err(crate::error::coded_details("PROJECT_AMBIGUOUS",false,format!("legacy project ID {} exists in more than one workspace; use workspace + project",legacy_project),json!({"project":legacy_project})));}resolved=Some(workspace_id);}
        }

        let workspace_id = resolved.ok_or_else(||crate::error::coded_details("PROJECT_NOT_AUTHORIZED",false,format!("no configured project matches legacy project ID {}",legacy_project),json!({"project":legacy_project})))?;

        self.project_exact(&workspace_id, legacy_project)
    }
    pub async fn wait_for_operations(&self){let until=Instant::now()+std::time::Duration::from_secs(30);loop{let current=self.projects_snapshot();let retired=self.retired_projects.lock().map(|v|v.clone()).unwrap_or_default();let busy=current.iter().map(|(_,p)|p).chain(retired.iter()).any(|p|p.lock.try_lock().is_err());if !busy||Instant::now()>=until{break;}tokio::time::sleep(std::time::Duration::from_millis(50)).await;}}
    pub fn body_limit(&self)->usize{self.config.limits.max_file_bytes.saturating_mul(6).saturating_add(65536)}
    pub fn workspace_project_counts(&self)->(usize,usize){let workspaces=self.workspaces_snapshot();(workspaces.len(),workspaces.values().map(|w|w.projects.len()).sum())}
    fn reload_authorization_inner(&self)->Result<Value>{
        let persisted=Config::load_file(&self.config_path)?;let service_revision=service_config_revision(&persisted)?;
        if service_revision!=self.active_service_revision{return Err(crate::error::coded("RELOAD_RESTART_REQUIRED",false,"service-level configuration changed; restart EndlessVibe before marking this config revision active"));}
        let mut next=workspace::load(&persisted,&self.config_path)?;let revision=config_edit::revision(&self.config_path)?;
        let old={let mut current=self.workspaces.write().unwrap_or_else(|e|e.into_inner());reuse_project_locks(&mut next,&current);std::mem::replace(&mut *current,next)};
        {let mut retired=self.retired_projects.lock().map_err(|_|anyhow::anyhow!("Retired project table poisoned"))?;retired.retain(|p|p.lock.try_lock().is_err());for project in old.values().flat_map(|w|w.projects.values()){if project.lock.try_lock().is_err()&&!retired.iter().any(|existing|Arc::ptr_eq(&existing.lock,&project.lock)){retired.push(project.clone());}}}
        *self.active_config_revision.write().unwrap_or_else(|e|e.into_inner())=revision.clone();let(workspace_count,project_count)=self.workspace_project_counts();let active_revision=revision.clone();
        Ok(json!({"revision":revision,"active_revision":active_revision,"requires_restart":false,"workspace_count":workspace_count,"project_count":project_count,"reloaded":true}))
    }
    pub fn dashboard_reload_config(&self)->Result<Value>{let operation=self.begin_operation("dashboard_reload_config","","",json!({}));let result=(||{let _guard=self.config_edit_lock.lock().map_err(|_|anyhow::anyhow!("Config edit lock poisoned"))?;let value=self.reload_authorization_inner()?;self.publish_dashboard("config_changed",value.clone());Ok(value)})();self.finish_operation(operation,result)}
    pub fn dashboard_storage_maintenance(&self)->Result<Value>{let operation=self.begin_operation("dashboard_storage_maintenance","","",json!({}));let result=self.db.maintain(self.config.limits.retained_jobs);self.finish_operation(operation,result)}
    pub fn dashboard_storage_health(&self)->Result<Value>{crate::storage::snapshot(&self.config.security.data_dir,&self.db,self.config.limits.retained_jobs)}
    pub async fn dashboard_sandbox_diagnostics(&self)->Result<Value>{let diagnostics=process::sandbox_diagnostics(&self.config).await?;let persisted_revision=config_edit::revision(&self.config_path)?;let active_revision=self.active_config_revision.read().unwrap_or_else(|e|e.into_inner()).clone();Ok(json!({"generated_at":util::now(),"persisted_revision":persisted_revision,"active_revision":active_revision,"requires_restart":persisted_revision!=active_revision,"diagnostics":diagnostics}))}
    pub fn snapshot(&self)->Value{let workspaces=self.workspaces_snapshot();let projects=workspaces.values().map(|w|w.projects.len()).sum::<usize>();let development_projects=workspaces.values().flat_map(|w|w.projects.values()).filter(|p|p.config.development()).count();let network_enabled=self.config.execution.backend=="host"||self.config.execution.allow_network||development_projects>0;json!({"status":"running","name":"EndlessVibe","version":env!("CARGO_PKG_VERSION"),"listen_address":self.config.server.bind.to_string(),"port":self.config.server.bind.port(),"uptime_seconds":self.started.elapsed().as_secs(),"started_at_unix_seconds":self.started_unix,"checked_at_unix_seconds":util::now(),"security":{"authentication":"oauth2_pkce","anonymous_private_tools":false,"execution_backend":self.config.execution.backend,"shell_enabled":self.config.execution.allow_shell,"network_enabled":network_enabled,"development_project_count":development_projects,"network_mode":if self.config.execution.backend=="host"{"host_always"}else if development_projects>0{"project_profiles"}else if self.config.execution.allow_network{"per_job_opt_in"}else{"isolated"},"network_isolation":if self.config.execution.backend=="host"{"none_host_permissions"}else if development_projects>0{"isolated projects stay isolated; development projects share host network by default"}else if self.config.execution.allow_network{"isolated_by_default; network=true shares host network"}else{"isolated_or_disabled"}},"dashboard":{"enabled":true,"listen_address":"127.0.0.1:20001","url":"http://127.0.0.1:20001/"},"workspace_count":workspaces.len(),"project_count":projects,"active_jobs":self.jobs.active_count(),"mcp":{"endpoint":"/mcp","method":"POST","transport":"streamable_http","session_mode":"stateless","protocol_version":"negotiated","implementation":"rmcp","sdk_version":crate::mcp::SDK_VERSION,"tool_schema_revision":crate::mcp::TOOL_SCHEMA_REVISION,"tool_count":crate::mcp::TOOL_NAMES.len(),"chatgpt_registration":"client_specific_not_asserted","tools":crate::mcp::TOOL_NAMES}})}
    pub fn dashboard_config(&self)->Result<Value>{let persisted=Config::load_file(&self.config_path)?;let revision=config_edit::revision(&self.config_path)?;let active_revision=self.active_config_revision.read().unwrap_or_else(|e|e.into_inner()).clone();let effective=workspace::load(&persisted,&self.config_path)?;let workspaces=effective.values().map(|w|json!({"id":w.config.id,"path":w.root.path,"project_count":w.projects.len(),"projects":w.projects.values().map(|p|p.summary()).collect::<Vec<_>>() })).collect::<Vec<_>>();let requires_restart=revision!=active_revision;Ok(json!({"revision":revision,"active_revision":active_revision,"requires_restart":requires_restart,"server":{"bind":persisted.server.bind.to_string(),"public_url":persisted.server.public_url,"allowed_hosts":persisted.server.allowed_hosts},"dashboard":{"listen_address":"127.0.0.1:20001","local_only":true},"security":{"authentication":"oauth2_pkce","allow_http_loopback":persisted.security.allow_http_loopback,"access_token_seconds":persisted.security.access_token_seconds,"refresh_token_seconds":persisted.security.refresh_token_seconds,"extra_redirect_uri_count":persisted.security.extra_redirect_uris.len()},"execution":{"backend":persisted.execution.backend,"allow_shell":persisted.execution.allow_shell,"allow_network":persisted.execution.allow_network,"auto_discover_toolchains":persisted.execution.auto_discover_toolchains,"bubblewrap":persisted.execution.bubblewrap,"path":persisted.execution.path,"allowed_programs":persisted.execution.allowed_programs,"required_programs":persisted.execution.required_programs,"readonly_mounts":persisted.execution.readonly_mounts.iter().map(|m|json!({"source":m.source,"target":m.target})).collect::<Vec<_>>(),"memory_limit_mb":persisted.execution.memory_limit_mb,"max_processes":persisted.execution.max_processes},"limits":{"max_file_bytes":persisted.limits.max_file_bytes,"max_read_bytes":persisted.limits.max_read_bytes,"max_output_bytes":persisted.limits.max_output_bytes,"command_timeout_seconds":persisted.limits.command_timeout_seconds,"max_jobs":persisted.limits.max_jobs,"retained_jobs":persisted.limits.retained_jobs,"search_max_files":persisted.limits.search_max_files,"search_max_bytes":persisted.limits.search_max_bytes},"git":{"executable":persisted.git.executable,"author_name":persisted.git.author_name,"author_email":persisted.git.author_email},"mcp":{"tool_schema_revision":crate::mcp::TOOL_SCHEMA_REVISION,"tool_count":crate::mcp::TOOL_NAMES.len(),"tools":crate::mcp::TOOL_NAMES},"workspaces":workspaces,"note":"Sensitive credentials and token material are intentionally omitted. Project authorization changes can be hot-reloaded; service-level changes still require restart."}))}
    pub fn dashboard_update_readonly_mounts(&self,request:UpdateReadonlyMountsRequest)->Result<Value>{let input=serde_json::to_value(&request).unwrap_or_else(|_|json!({}));let operation=self.begin_operation("dashboard_update_readonly_mounts","","",input);let result=(||{let _guard=self.config_edit_lock.lock().map_err(|_|anyhow::anyhow!("Config edit lock poisoned"))?;let result=config_edit::update_readonly_mounts(&self.config_path,request)?;let value=serde_json::to_value(&result)?;self.publish_dashboard("config_changed",json!({"revision":result.revision,"requires_restart":true}));Ok(value)})();self.finish_operation(operation,result)}
    pub fn dashboard_add_project(&self,request:AddProjectRequest)->Result<Value>{let input=serde_json::to_value(&request).unwrap_or_else(|_|json!({}));let workspace=request.workspace.clone();let project=request.project.clone().unwrap_or_default();let operation=self.begin_operation("dashboard_add_project",&workspace,&project,input);let result=(||{let _guard=self.config_edit_lock.lock().map_err(|_|anyhow::anyhow!("Config edit lock poisoned"))?;let mut result=config_edit::add_project(&self.config_path,request)?;match self.reload_authorization_inner(){Ok(_)=>result.requires_restart=false,Err(error)=>{result.requires_restart=true;result.reload_warning=Some(format!("{error:#}"));}}let value=serde_json::to_value(&result)?;self.publish_dashboard("config_changed",json!({"revision":result.revision,"requires_restart":result.requires_restart}));Ok(value)})();self.finish_operation(operation,result)}
    pub fn dashboard_update_project(&self,workspace:&str,project:&str,request:UpdateProjectRequest)->Result<Value>{let input=serde_json::to_value(&request).unwrap_or_else(|_|json!({}));let operation=self.begin_operation("dashboard_update_project",workspace,project,input);let result=(||{let _guard=self.config_edit_lock.lock().map_err(|_|anyhow::anyhow!("Config edit lock poisoned"))?;let mut result=config_edit::update_project(&self.config_path,workspace,project,request)?;match self.reload_authorization_inner(){Ok(_)=>result.requires_restart=false,Err(error)=>{result.requires_restart=true;result.reload_warning=Some(format!("{error:#}"));}}let value=serde_json::to_value(&result)?;self.publish_dashboard("config_changed",json!({"revision":result.revision,"requires_restart":result.requires_restart}));Ok(value)})();self.finish_operation(operation,result)}
    pub fn begin_operation(&self,tool:&str,workspace:&str,project:&str,input:Value)->OperationTrace{let task_id=input.get("task_id").and_then(Value::as_str).map(str::to_owned);let stage=input.get("stage").and_then(Value::as_str).map(str::to_owned);let id=self.db.operation_start(tool,workspace,project,&input).map_err(|error|tracing::warn!(error=%error,tool=%tool,"Could not start operation log")).ok();OperationTrace{id,started:Instant::now(),tool:tool.into(),workspace:workspace.into(),project:project.into(),task_id,stage}}
    pub fn finish_operation(&self,operation:OperationTrace,mut result:Result<Value>)->Result<Value>{let duration_ms=operation.started.elapsed().as_millis() as u64;let mut diff=String::new();let(status,output,error_code,error)=match &mut result{Ok(value)=>{if let Some(object)=value.as_object_mut(){if let Some(value)=object.remove("_operation_diff"){if let Some(text)=value.as_str(){diff=text.to_owned();}}else if let Some(text)=object.get("diff").and_then(Value::as_str){diff=text.to_owned();}}let mut logged=value.clone();if !diff.is_empty(){if let Some(object)=logged.as_object_mut(){if object.contains_key("diff"){object.insert("diff".into(),json!({"stored_separately":true,"bytes":diff.len()}));}}}("succeeded",Some(logged),"",String::new())},Err(error)=>("failed",None,crate::error::code(error),format!("{error:#}"))};if let Some(id)=operation.id{if let Err(log_error)=self.db.operation_finish(id,status,duration_ms,output.as_ref(),&diff,error_code,&error){tracing::warn!(error=%log_error,operation_id=id,"Could not finish operation log");}else{self.publish_dashboard("operation_created",json!({"seq":id,"status":status,"error_code":error_code,"duration_ms":duration_ms}));let task=operation.task_id.as_deref().or_else(||result.as_ref().ok().and_then(|v|v.get("task_id")).and_then(Value::as_str));let stage=operation.stage.as_deref().or_else(||result.as_ref().ok().and_then(|v|v.get("stage")).and_then(Value::as_str));if let(Some(task),Some(stage))=(task,stage){if tasks::validate_context(&Some(task.into()),&Some(stage.into())).is_ok(){let workspace=result.as_ref().ok().and_then(|v|v.get("canonical_workspace")).and_then(Value::as_str).unwrap_or(&operation.workspace);let project=result.as_ref().ok().and_then(|v|v.get("canonical_project")).and_then(Value::as_str).unwrap_or(&operation.project);if let Ok(p)=self.project(workspace,project){if let Err(error)=tasks::record_operation(&self.db,&p.workspace_id,&p.config.id,task,stage,id,&operation.tool,status){tracing::warn!(error=%error,operation_id=id,"Could not link operation to task");}}}}}}result}
    pub fn publish_dashboard(&self,event:&str,data:Value){let _=self.dashboard_events.send(json!({"type":event,"time":util::now(),"data":data}).to_string());}
    pub fn subscribe_dashboard(&self)->broadcast::Receiver<String>{self.dashboard_events.subscribe()}
    pub fn record_http_traffic(&self,rx:u64,tx:u64){self.traffic_requests.fetch_add(1,Ordering::Relaxed);self.traffic_rx.fetch_add(rx,Ordering::Relaxed);self.traffic_tx.fetch_add(tx,Ordering::Relaxed);}
    pub fn take_http_traffic(&self)->(u64,u64,u64){(self.traffic_requests.swap(0,Ordering::AcqRel),self.traffic_rx.swap(0,Ordering::AcqRel),self.traffic_tx.swap(0,Ordering::AcqRel))}
    pub fn workspaces_summary(&self)->Value{let workspaces=self.workspaces_snapshot();json!({"workspaces":workspaces.values().map(|w|w.summary()).collect::<Vec<_>>()})}
    pub fn projects_for(&self,workspace:&str)->Result<Value>{Ok(self.workspace_root(workspace)?.projects_summary())}
    fn finish(&self,tool:&str,id:&str,result:Result<Value>)->Result<Value>{let outcome=if result.is_ok(){"succeeded"}else{"failed"};let audit=self.db.audit(tool,id,outcome,"");self.publish_dashboard("activity_changed",json!({"tool":tool,"target":id,"outcome":outcome}));match result{Ok(mut value)=>{if audit.is_err(){value["audit_warning"]=json!("Operation completed but final audit record failed; the started record is retained");}Ok(value)},Err(e)=>Err(e)}}
    pub async fn sync_project<F>(self:&Arc<Self>,tool:&'static str,workspace:&str,project:&str,f:F)->Result<Value> where F:FnOnce(Arc<Runtime>,Arc<Project>)->Result<Value>+Send+'static{let p=self.project(workspace,project)?;let key=format!("{workspace}/{project}");let lock=p.lock.clone().try_lock_owned().map_err(|_|crate::error::coded_details("PROJECT_BUSY",true,"another file/Git/command operation is active",json!({"workspace":workspace,"project":project})))?;self.db.audit(tool,&key,"started","")?;self.publish_dashboard("activity_changed",json!({"tool":tool,"target":key,"outcome":"started"}));let rt=self.clone();let result=tokio::task::spawn_blocking(move||{let _lock=lock;f(rt,p)}).await.context("File worker panicked")?;self.finish(tool,&key,result)}
    pub async fn asynchronous_project<F,Fut>(self:&Arc<Self>,tool:&'static str,workspace:&str,project:&str,f:F)->Result<Value> where F:FnOnce(Arc<Runtime>,Arc<Project>)->Fut+Send+'static,Fut:Future<Output=Result<Value>>+Send+'static{let p=self.project(workspace,project)?;let lock=p.lock.clone().try_lock_owned().map_err(|_|crate::error::coded_details("PROJECT_BUSY",true,"another file/Git/command operation is active",json!({"workspace":workspace,"project":project})))?;let key=format!("{workspace}/{project}");self.db.audit(tool,&key,"started","")?;self.publish_dashboard("activity_changed",json!({"tool":tool,"target":key,"outcome":"started"}));let this=self.clone();tokio::spawn(async move{let _lock=lock;let result=f(this.clone(),p).await;this.finish(tool,&key,result)}).await.context("Git worker panicked")?}
}

#[cfg(test)]mod tests{
    use super::*;
    #[test]fn service_revision_ignores_workspace_authorization(){let a=Config::default();let mut b=a.clone();b.workspaces.push(crate::config::WorkspaceConfig{id:"root".into(),path:"/tmp/root".into(),projects:vec![],allow_write:None,allow_exec:None,allow_git_commit:None,allow_git_mutation:None,allow_git_push:None,execution_profile:None,environment:vec![]});assert_eq!(service_config_revision(&a).unwrap(),service_config_revision(&b).unwrap());b.execution.allow_shell=!b.execution.allow_shell;assert_ne!(service_config_revision(&a).unwrap(),service_config_revision(&b).unwrap());}
    #[test]fn reload_reuses_project_locks(){let t=tempfile::tempdir().unwrap();let state=t.path().join("state");let root=t.path().join("root");std::fs::create_dir_all(&state).unwrap();std::fs::create_dir_all(root.join("app")).unwrap();let cfg_path=t.path().join("config.toml");std::fs::write(&cfg_path,"").unwrap();let mut cfg=Config::default();cfg.security.data_dir=state;cfg.workspaces=vec![crate::config::WorkspaceConfig{id:"root".into(),path:root,projects:vec![crate::config::ProjectConfig{id:"app".into(),path:"app".into(),allow_write:true,allow_exec:true,allow_git_commit:true,allow_git_mutation:false,allow_git_push:false,execution_profile:crate::config::default_project_profile(),environment:vec![]}],allow_write:None,allow_exec:None,allow_git_commit:None,allow_git_mutation:None,allow_git_push:None,execution_profile:None,environment:vec![]}];let old=workspace::load(&cfg,&cfg_path).unwrap();let mut next=workspace::load(&cfg,&cfg_path).unwrap();assert!(!Arc::ptr_eq(&old["root"].projects["app"].lock,&next["root"].projects["app"].lock));reuse_project_locks(&mut next,&old);assert!(Arc::ptr_eq(&old["root"].projects["app"].lock,&next["root"].projects["app"].lock));}
}
