import {$,setText,formatTime,formatShortTime,formatUptime,formatBytes,node,outcomeClass,displayValue} from "./js/common.js";
import {renderToolTree} from "./js/mcp.js";
import {renderMetrics,resizePlots} from "./js/charts.js";

"use strict";
const currentPage=location.pathname==="/projects"?"projects":location.pathname==="/tasks"?"tasks":location.pathname==="/activity"?"activity":location.pathname==="/operations"?"operations":location.pathname==="/mcp"?"mcp":location.pathname==="/config"?"config":"home";
const pageNames={home:"首页",projects:"Projects",tasks:"Tasks",activity:"活动",operations:"操作日志",mcp:"MCP",config:"配置"};
const pendingEvents=new Set();
let busy=false,eventSource=null,eventRefreshTimer=null,hiddenDirty=false,serviceOnline=false,configRevision="",uptimeSnapshot=0,uptimeReceivedAt=0;
function setWriteStatus(message,state="neutral"){const el=$("config-write-status");if(!el)return;el.textContent=message||"";el.className=`write-status ${state}`;}
function setReloadStatus(message,state="neutral"){const el=$("config-reload-status");if(!el)return;el.textContent=message||"";el.className=`write-status ${state}`;}
function activatePage(){document.querySelectorAll("[data-page]").forEach(el=>el.hidden=el.dataset.page!==currentPage);document.querySelectorAll("[data-nav]").forEach(el=>el.classList.toggle("active",el.dataset.nav===currentPage));setText("breadcrumb-current",pageNames[currentPage]);document.title=`EndlessVibe · ${pageNames[currentPage]}`;}
function setConnection(online,label){serviceOnline=online;const badge=$("header-status");if(!badge)return;badge.className=`header-status ${online?"online":"offline"}`;setText("header-status-text",label||(online?"运行中":"离线"));}
function renderAudits(id,audits,limit){const host=$(id);if(!host)return;host.replaceChildren();const rows=(audits||[]).slice(0,limit);if(!rows.length){host.className="activity-list empty-state";host.textContent="暂无活动";return;}host.className="activity-list";for(const item of rows){const row=node("div","activity-row"),main=node("div","activity-main"),meta=node("div","activity-meta");main.append(node("strong","activity-tool",item.tool||"—"),node("span","activity-target",item.workspace||"—"));meta.append(node("span",`state ${outcomeClass(item.outcome)}`,item.outcome||"—"),node("time","",formatShortTime(item.time)));row.append(main,meta);host.appendChild(row);}}
function renderJobs(id,jobs,limit){const host=$(id);if(!host)return;host.replaceChildren();const rows=(jobs||[]).slice(0,limit);if(!rows.length){host.className="activity-list empty-state";host.textContent="暂无任务";return;}host.className="activity-list";for(const item of rows){const row=node("div","activity-row"),main=node("div","activity-main"),meta=node("div","activity-meta"),target=item.project?`${item.workspace}/${item.project}`:item.workspace||"—";main.append(node("strong","activity-tool",item.program||"—"),node("span","activity-target",target));meta.append(node("span",`state ${outcomeClass(item.status)}`,item.status||"—"),node("time","",formatShortTime(item.created)));row.append(main,meta);host.appendChild(row);}}
function checkpointClass(status){const value=String(status||"").replace(/^job_/,"");return value==="committed"||value==="succeeded"?"good":value==="queued"||value==="running"||value==="started"?"active":["failed","timed_out","cancelled","interrupted"].includes(value)?"bad":"neutral";}
function checkpointLabel(status){return String(status||"—").replace(/^job_/,"");}
function renderTasks(checkpoints){const host=$("task-board");if(!host)return;host.replaceChildren();const grouped=new Map();for(const cp of checkpoints||[]){const key=`${cp.workspace}/${cp.project}/${cp.task_id}`;if(!grouped.has(key))grouped.set(key,{workspace:cp.workspace,project:cp.project,task_id:cp.task_id,stages:[],updated:0});const task=grouped.get(key);task.stages.push(cp);task.updated=Math.max(task.updated,Number(cp.updated)||0);}const tasks=[...grouped.values()].sort((a,b)=>b.updated-a.updated);if(!tasks.length){host.className="task-board empty-state";host.textContent="暂无 Task checkpoint";return;}host.className="task-board";for(const task of tasks){task.stages.sort((a,b)=>(Number(a.created)||0)-(Number(b.created)||0)||(Number(a.updated)||0)-(Number(b.updated)||0));const latest=task.stages.reduce((a,b)=>(Number(a.updated)||0)>=(Number(b.updated)||0)?a:b);const details=node("details","task-card");details.open=true;const summary=node("summary","task-summary"),title=node("div","task-title"),meta=node("div","task-summary-meta");title.append(node("strong","",task.task_id),node("span","mono-value",`${task.workspace}/${task.project}`));meta.append(node("span",`task-state ${checkpointClass(latest.status)}`,checkpointLabel(latest.status)),node("time","",formatTime(latest.updated)));summary.append(title,meta);const stages=node("div","task-stages");for(const stage of task.stages){const row=node("section","task-stage"),head=node("div","task-stage-head"),name=node("strong","",stage.stage),state=node("span",`task-state ${checkpointClass(stage.status)}`,checkpointLabel(stage.status));head.append(name,state);row.appendChild(head);const info=node("div","task-stage-info");info.append(node("span","",`updated ${formatTime(stage.updated)}`));if(stage.last_commit)info.append(node("code","task-commit",`commit ${String(stage.last_commit).slice(0,12)}`));row.appendChild(info);if((stage.jobs||[]).length){const jobs=node("div","task-jobs");for(const job of stage.jobs){const item=node("div","task-job"),id=node("code","",job.job_id),jobState=node("span",`task-state ${checkpointClass(job.status)}`,checkpointLabel(job.status)),time=node("time","",formatTime(job.updated));item.append(id,jobState,time);jobs.appendChild(item);}row.appendChild(jobs);}stages.appendChild(row);}details.append(summary,stages);host.appendChild(details);}}
function operationTarget(item){return item.workspace?(item.project?`${item.workspace}/${item.project}`:item.workspace):"service";}
function compactJson(value,max=520){let text;try{text=JSON.stringify(value??{},null,2);}catch{text=String(value??"");}return text.length>max?`${text.slice(0,max)}\n…`:text;}
function compactDiff(item){const count=(item.added_lines||item.removed_lines)?`+${item.added_lines||0} -${item.removed_lines||0}\n`:"";const diff=String(item.diff_preview||"");if(!diff)return count||"—";const text=count+diff;return text.length>760?`${text.slice(0,760)}\n…`:text;}
function renderOperations(items){const host=$("operation-list");if(!host)return;const openIds=new Set([...host.querySelectorAll("details[open]")].map(el=>el.dataset.id));const previousScroll=host.scrollTop;const atTop=previousScroll<24;host.replaceChildren();if(!(items||[]).length){host.className="operation-stream empty-state";host.textContent="暂无操作日志";return;}host.className="operation-stream";for(const item of items){const details=node("details","operation-entry timeline-entry");details.dataset.id=String(item.seq);const summary=node("summary","operation-summary-grid");const timeline=node("div","operation-timeline-cell"),time=node("time","operation-time",formatShortTime(item.started)),dot=node("span",`timeline-dot ${outcomeClass(item.status)}`);timeline.append(time,dot);const operation=node("div","operation-id-cell"),id=node("strong","operation-id",`#${item.seq}`),tool=node("span","operation-tool",item.tool||"—"),target=node("span","operation-target",operationTarget(item)),meta=node("span","operation-inline-meta",`${item.status||"—"}${item.error_code?` · ${item.error_code}`:""} · ${item.duration_ms||0} ms`);operation.append(id,tool,target,meta);const input=node("pre","operation-cell-preview input-preview");input.textContent=compactJson(item.input_preview);const diff=node("pre","operation-cell-preview diff-preview");diff.textContent=compactDiff(item);summary.append(timeline,operation,input,diff);const body=node("div","operation-detail operation-loading","展开后加载完整 Input / Diff / Output…");details.append(summary,body);details.addEventListener("toggle",()=>{if(details.open&&!details.dataset.loaded)loadOperationDetail(details);});if(openIds.has(String(item.seq))){details.open=true;queueMicrotask(()=>loadOperationDetail(details));}host.appendChild(details);}host.scrollTop=atTop?0:previousScroll;}
function jsonSection(title,value){const section=node("section","operation-section"),heading=node("h4","",title),pre=node("pre","operation-json");pre.textContent=JSON.stringify(value??{},null,2);section.append(heading,pre);return section;}
function diffSection(diff){const section=node("section","operation-section"),heading=node("h4","","Diff"),pre=node("pre","operation-diff");for(const line of String(diff||"").split("\n")){let cls="diff-context";if(line.startsWith("+")&&!line.startsWith("+++"))cls="diff-add";else if(line.startsWith("-")&&!line.startsWith("---"))cls="diff-remove";else if(line.startsWith("@@")||line.startsWith("---")||line.startsWith("+++"))cls="diff-meta";const span=node("span",cls,line);pre.appendChild(span);pre.appendChild(document.createTextNode("\n"));}section.append(heading,pre);return section;}
async function loadOperationDetail(details){if(details.dataset.loaded==="loading"||details.dataset.loaded==="true")return;details.dataset.loaded="loading";const body=details.querySelector(".operation-detail");body.className="operation-detail operation-loading";body.textContent="加载详情…";try{const detail=await getJson(`/api/operations/${encodeURIComponent(details.dataset.id)}`);body.replaceChildren();body.className="operation-detail timeline-detail";const meta=node("div","operation-detail-meta");for(const [label,value] of [["Operation",`#${detail.seq}`],["Started",formatTime(detail.started)],["Finished",detail.finished?formatTime(detail.finished):"—"],["Duration",`${detail.duration_ms||0} ms`],["Target",operationTarget(detail)],["Error Code",detail.error_code||"—"]]){const item=node("div","");item.append(node("span","",label),node("strong","",value));meta.appendChild(item);}body.appendChild(meta);const primary=node("div","operation-detail-primary");primary.append(jsonSection("Input",detail.input),detail.diff?diffSection(detail.diff):jsonSection("Diff",{"changed":false}));body.appendChild(primary);const secondary=node("div","operation-detail-secondary");secondary.append(jsonSection("Output",detail.output));if(detail.error){const errorSection=node("section","operation-section operation-error"),heading=node("h4","","Error"),pre=node("pre","operation-json");pre.textContent=detail.error;errorSection.append(heading,pre);secondary.appendChild(errorSection);}body.appendChild(secondary);const jobId=detail.output?.job_id;if(jobId){const jobSection=node("section","operation-section"),heading=node("h4","","Job Output"),pre=node("pre","operation-job-output","加载任务输出…");jobSection.append(heading,pre);body.appendChild(jobSection);try{const job=await getJson(`/api/jobs/${encodeURIComponent(jobId)}`);pre.textContent=job.output?.output||"(no output)";const state=node("div","job-detail-state",`status: ${job.job?.status||"—"} · exit: ${job.job?.exit_code??"—"}`);jobSection.insertBefore(state,pre);}catch(error){pre.textContent=error.message;}}details.dataset.loaded="true";}catch(error){body.className="operation-detail operation-error";body.textContent=error.message;details.dataset.loaded="";}}
function expandAllOperations(){document.querySelectorAll("#operation-list details.operation-entry").forEach(details=>{details.open=true;});}
function collapseAllOperations(){document.querySelectorAll("#operation-list details.operation-entry").forEach(details=>{details.open=false;});}
function renderConfigList(id,rows){const host=$(id);if(!host)return;host.replaceChildren();for(const [label,value] of rows){const wrap=node("div","config-row");wrap.append(node("dt","",label),node("dd","mono-value",displayValue(value)));host.appendChild(wrap);}}
function permissionToggle(key,checked,label=key){const wrapper=node("label","permission-toggle");const input=document.createElement("input");input.type="checkbox";input.checked=!!checked;input.dataset.permission=key;wrapper.append(input,document.createTextNode(` ${label}`));return wrapper;}
function renderWorkspaceConfig(workspaces){const host=$("workspace-config");if(!host)return;host.replaceChildren();for(const workspace of workspaces||[]){const card=node("article","workspace-card"),head=node("div","workspace-head"),title=node("div");title.append(node("strong","",workspace.id),node("span","mono-value",workspace.path));head.append(title,node("span","count-badge",`${workspace.project_count} projects`));card.appendChild(head);const projects=node("div","project-list");for(const project of workspace.projects||[]){const row=node("div","project-row"),left=node("div","project-main"),form=node("form","permission-editor project-permission-form"),git=node("span","project-git-summary","Git · checking");git.dataset.projectKey=`${workspace.id}/${project.id}`;left.append(node("strong","",project.id),node("span","mono-value",project.path),git);form.dataset.workspace=workspace.id;form.dataset.project=project.id;form.append(node("span","permission-title","权限"),permissionToggle("write",project.allow_write),permissionToggle("exec",project.allow_exec),permissionToggle("commit",project.allow_git_commit),permissionToggle("mutation",project.allow_git_mutation,"git rw"),permissionToggle("push",project.allow_git_push,"push"));const save=node("button","small-button","保存");save.type="submit";form.appendChild(save);row.append(left,form);projects.appendChild(row);}card.appendChild(projects);host.appendChild(card);}if(!(workspaces||[]).length)host.textContent="暂无 Workspace";}
function renderProjectStates(items){const states=new Map((items||[]).map(item=>[`${item.workspace}/${item.project}`,item]));document.querySelectorAll(".project-git-summary[data-project-key]").forEach(el=>{const item=states.get(el.dataset.projectKey);if(!item){el.textContent="Git · unavailable";el.className="project-git-summary unavailable";return;}if(item.state==="ready"){const head=String(item.head||"—");const shortHead=head==="UNBORN"?"UNBORN":head.slice(0,8),branch=item.branch||"detached",change=item.dirty?`dirty ${item.changes||0}`:"clean";el.textContent=`Git · ${branch} · ${shortHead} · ${change}`;el.className=`project-git-summary ${item.dirty?"dirty":"clean"}`;}else{const label=item.state==="not_repository"?"not a repository":item.state;el.textContent=`Git · ${label}`;el.className=`project-git-summary ${item.state}`;}});}
function renderWorkspaceOptions(workspaces){const select=$("add-project-workspace");if(!select)return;const selected=select.value;select.replaceChildren();for(const workspace of workspaces||[]){const option=document.createElement("option");option.value=workspace.id;option.textContent=`${workspace.id} — ${workspace.path}`;select.appendChild(option);}if([...select.options].some(o=>o.value===selected))select.value=selected;}
function renderStorage(data){const db=data.database||{},logical=db.logical||{},dirs=data.directories||{},state=data.state||{};const dir=(name)=>dirs[name]||{};renderConfigList("config-storage",[["Schema",`${logical.schema_version??"—"} / current ${logical.schema_current??"—"}`],["SQLite Physical",formatBytes(db.physical_bytes)],["SQLite Main",formatBytes(db.main_bytes)],["SQLite WAL",formatBytes(db.wal_bytes)],["SQLite SHM",formatBytes(db.shm_bytes)],["SQLite Logical",formatBytes(logical.logical_bytes)],["SQLite Free",formatBytes(logical.free_bytes)],["State Total",`${formatBytes(state.bytes)} · ${state.nodes??0} nodes${state.truncated?" · truncated":""}`],["Exec Cache",formatBytes(dir("exec_cache").bytes)],["Backups",formatBytes(dir("backups").bytes)],["Git Journal",formatBytes(dir("git_journal").bytes)],["Temp",formatBytes(dir("tmp").bytes)],["Rows",`jobs ${logical.rows?.jobs??0} · audit ${logical.rows?.audit??0} · ops ${logical.rows?.operations??0} · tasks ${logical.rows?.task_checkpoints??0}`],["Retention",`jobs ${logical.retention?.retained_jobs??0} · audit ${logical.retention?.audit_rows??0} · ops ${logical.retention?.operation_rows??0} · tasks ${logical.retention?.task_checkpoints??0} · traffic ${Math.round((logical.retention?.traffic_seconds??0)/86400)}d`]]);setText("storage-updated",`更新于 ${formatTime(data.generated_at)}`);}
function renderConfig(data){configRevision=data.revision||"";renderConfigList("config-server",[["Bind",data.server?.bind],["Public URL",data.server?.public_url],["Allowed Hosts",data.server?.allowed_hosts],["Dashboard",data.dashboard?.listen_address],["Local Only",data.dashboard?.local_only]]);renderConfigList("config-security",[["Authentication",data.security?.authentication],["HTTP Loopback",data.security?.allow_http_loopback],["Access Token",`${data.security?.access_token_seconds??0}s`],["Refresh Token",`${data.security?.refresh_token_seconds??0}s`],["Extra Redirect URIs",data.security?.extra_redirect_uri_count]]);renderConfigList("config-execution",[["Backend",data.execution?.backend],["Shell",data.execution?.allow_shell],["Network",data.execution?.allow_network],["Auto Toolchains",data.execution?.auto_discover_toolchains],["Bubblewrap",data.execution?.bubblewrap],["PATH",data.execution?.path],["Allowed Programs",data.execution?.allowed_programs],["Required Programs",data.execution?.required_programs],["Readonly Mounts",(data.execution?.readonly_mounts||[]).map(m=>`${m.source} → ${m.target}`)],["Persisted Revision",data.revision],["Active Revision",data.active_revision],["Config State",data.requires_restart?"Pending restart":"Active"],["Memory",`${data.execution?.memory_limit_mb??0} MiB`],["Max Processes",data.execution?.max_processes]]);renderConfigList("config-limits",[["Max File",formatBytes(data.limits?.max_file_bytes)],["Max Read",formatBytes(data.limits?.max_read_bytes)],["Max Output",formatBytes(data.limits?.max_output_bytes)],["Command Timeout",`${data.limits?.command_timeout_seconds??0}s`],["Max Jobs",data.limits?.max_jobs],["Retained Jobs",data.limits?.retained_jobs],["Search Max Files",data.limits?.search_max_files],["Search Max Bytes",formatBytes(data.limits?.search_max_bytes)]]);renderConfigList("config-git",[["Executable",data.git?.executable],["Author",data.git?.author_name],["Email",data.git?.author_email]]);renderWorkspaceConfig(data.workspaces);renderWorkspaceOptions(data.workspaces);for(const id of ["config-restart-badge","projects-restart-badge"]){const badge=$(id);if(badge){badge.textContent=data.requires_restart?"Pending restart":"已生效";badge.classList.toggle("pending-restart",!!data.requires_restart);}}}
function renderStatus(data){setConnection(true);uptimeSnapshot=data.uptime_seconds||0;uptimeReceivedAt=Date.now();setText("version",`v${data.version}`);setText("uptime",formatUptime(uptimeSnapshot));setText("workspace-count",data.workspace_count);setText("project-count",data.project_count);setText("active-jobs",data.active_jobs);setText("execution-backend",data.security?.execution_backend);setText("status-title","服务运行正常");setText("status-detail","MCP 与本地 Dashboard 均已响应；实时更新由 SSE 事件驱动。");setText("last-success",`最近成功检查：${formatTime(data.checked_at_unix_seconds)}`);const toolCount=data.mcp?.tool_count??(Array.isArray(data.mcp?.tools)?data.mcp.tools.length:0);setText("mcp-tool-count",`${toolCount} tools`);renderConfigList("mcp-connection",[["Endpoint",data.mcp?.endpoint],["Listen",data.listen_address],["Authentication",data.security?.authentication]]);renderConfigList("mcp-runtime",[["Server Version",data.version],["Tool Schema",data.mcp?.tool_schema_revision],["Tool Count",toolCount],["Transport",data.mcp?.transport],["Session",data.mcp?.session_mode],["Protocol",data.mcp?.protocol_version],["SDK",data.mcp?.sdk_version]]);setText("mcp-schema-note",`服务端工具 schema revision：${data.mcp?.tool_schema_revision??"—"}。如果这里的 revision / tool count 已更新，但 ChatGPT 中仍缺少新工具，说明客户端仍缓存旧 schema，需要重新连接或刷新 EndlessVibe 插件。`);renderToolTree("mcp-tools",data.mcp?.tools||[]);}
function responseError(data,fallback,status){const payload=data?.error&&typeof data.error==="object"?data.error:data||{};const message=typeof payload.message==="string"?payload.message:typeof data?.error==="string"?data.error:fallback;return Object.assign(new Error(message),{status,code:payload.code||null,retryable:payload.retryable===true,details:payload.details||{}});}
async function getJson(url,signal){const response=await fetch(url,{cache:"no-store",headers:{Accept:"application/json"},signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw responseError(data,`${url} HTTP ${response.status}`,response.status);return data;}
async function sendJson(url,method,body){const response=await fetch(url,{method,cache:"no-store",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw responseError(data,`${method} ${url} HTTP ${response.status}`,response.status);return data;}
async function refreshStatus(){renderStatus(await getJson("/api/status"));}
async function refreshMetrics(){renderMetrics(await getJson("/api/metrics"));}
async function refreshActivity(){const activity=await getJson("/api/activity");renderAudits("audit-list",activity.audits,40);renderJobs("job-list",activity.jobs,30);}
async function refreshOperations(){if(currentPage!=="operations")return;const data=await getJson("/api/operations?limit=100");renderOperations(data.operations);setText("operation-updated",`更新于 ${formatShortTime(data.generated_at)}`);}
async function refreshTasks(){const data=await getJson("/api/tasks?limit=200");renderTasks(data.checkpoints);setText("tasks-updated",`更新于 ${formatTime(data.generated_at)}`);}
function renderSandboxDiagnostics(data){const diag=data.diagnostics||{},host=$("sandbox-program-list"),suggested=diag.suggested_config||{};renderConfigList("config-sandbox-summary",[["Backend",diag.backend],["Host OS",diag.host_os],["PATH",diag.path],["Network",diag.network],["Shell",diag.shell],["Persisted Revision",data.persisted_revision],["Active Revision",data.active_revision],["Config State",data.requires_restart?"Pending restart":"Active"],["Readonly Mounts",(diag.readonly_mounts||[]).map(m=>`${m.source} → ${m.target} · ${m.source_exists?"source ok":"source missing"} · ${m.target_allowed?"target ok":"target invalid"}`)],["Suggested PATH Prefix",(suggested.prepend_path_entries||[]).join(":")||"—"],["Suggested Readonly Mounts",(suggested.readonly_mounts||[]).map(m=>`${m.source} → ${m.target}`)],["Suggested TOML",suggested.toml||"—"]]);if(host){host.replaceChildren();const programs=diag.programs||[];if(!programs.length){host.className="activity-list empty-state";host.textContent="没有诊断程序";}else{host.className="activity-list";for(const item of programs){const row=node("div","activity-row"),main=node("div","activity-main"),meta=node("div","activity-meta"),sandbox=item.sandbox_path||"—",hostPath=item.host_path||"—",suggestion=item.suggestion||null;main.append(node("strong","activity-tool",item.program),node("span","activity-target",`sandbox: ${sandbox}`),node("span","activity-target",`host: ${hostPath}`));if(item.reason)main.append(node("span","activity-target",`reason: ${item.reason}`));if(item.install_hint)main.append(node("span","activity-target",`install: ${item.install_hint}`));if(suggestion){const mount=suggestion.kind==="readonly-mount"?`${suggestion.source} → ${suggestion.target}`:"no extra mount";main.append(node("span","activity-target",`suggest: ${mount} · PATH ${suggestion.path_entry}`));}const cls=item.status==="available"?"good":item.status==="host-only"?"neutral":"bad";meta.append(node("span",`state ${cls}`,item.status),node("span","",`${item.required?"required ":""}${item.allowed?"allowed":""}`.trim()||"diagnostic"));row.append(main,meta);host.appendChild(row);}}setText("sandbox-updated",`更新于 ${formatTime(data.generated_at)}`);}
async function refreshStorage(){renderStorage(await getJson("/api/storage"));}
async function refreshConfig(){const[data,storage]=await Promise.all([getJson("/api/config"),getJson("/api/storage")]);renderConfig(data);renderStorage(storage);}
async function refreshProjectStates(){renderProjectStates((await getJson("/api/projects/status")).projects);}
async function refreshProjects(){const[data,states]=await Promise.all([getJson("/api/config"),getJson("/api/projects/status")]);renderConfig(data);renderProjectStates(states.projects);}
async function refresh(){if(busy)return;busy=true;const button=$("refresh");if(button){button.disabled=true;button.textContent="刷新中…";}try{await refreshStatus();if(currentPage==="projects")await refreshProjects();if(currentPage==="tasks")await refreshTasks();if(currentPage==="activity")await Promise.all([refreshMetrics(),refreshActivity()]);if(currentPage==="operations")await refreshOperations();if(currentPage==="config")await refreshConfig();}catch(error){setConnection(false);setText("status-title","暂时无法获取状态");setText("status-detail",error.message);}finally{busy=false;if(button){button.disabled=false;button.textContent="立即刷新";}}}
async function refreshForEvents(types){try{const tasks=[];if(types.has("job_changed"))tasks.push(refreshStatus());if(currentPage==="activity"){if(types.has("metrics_changed")||types.has("activity_changed")||types.has("job_changed"))tasks.push(refreshMetrics());if(types.has("activity_changed")||types.has("job_changed"))tasks.push(refreshActivity());}if(currentPage==="operations"&&types.has("operation_created"))tasks.push(refreshOperations());if(currentPage==="tasks"&&(types.has("job_changed")||types.has("operation_created")))tasks.push(refreshTasks());if(currentPage==="projects"){if(types.has("config_changed"))tasks.push(refreshProjects());else if(types.has("job_changed")||types.has("operation_created"))tasks.push(refreshProjectStates());}if(currentPage==="config"&&types.has("config_changed"))tasks.push(refreshConfig());await Promise.all(tasks);}catch(error){setConnection(false,"事件刷新失败");}}
function scheduleEventRefresh(type){pendingEvents.add(type);if(document.hidden){hiddenDirty=true;return;}clearTimeout(eventRefreshTimer);eventRefreshTimer=setTimeout(()=>{const types=new Set(pendingEvents);pendingEvents.clear();refreshForEvents(types);},180);}
function connectEvents(){if(!("EventSource"in window)){setInterval(()=>{if(!document.hidden)refresh();},5000);return;}eventSource?.close();eventSource=new EventSource("/api/events");eventSource.onopen=()=>{if(serviceOnline)setConnection(true,"运行中 · SSE");};eventSource.onmessage=event=>{try{const message=JSON.parse(event.data);if(message?.type)scheduleEventRefresh(message.type);}catch{}};eventSource.onerror=()=>{if(serviceOnline)setConnection(true,"SSE 重连中");};}
async function handleAddProject(event){event.preventDefault();const form=event.currentTarget,path=$("add-project-path").value.trim(),project=$("add-project-id").value.trim(),workspace=$("add-project-workspace").value,write=$("add-project-write").checked,exec=$("add-project-exec").checked,commit=$("add-project-commit").checked,mutation=$("add-project-git-mutation").checked,push=$("add-project-git-push").checked;if(!workspace){setWriteStatus("请选择 Workspace","error");return;}if(!path){setWriteStatus("Absolute Path 不能为空","error");return;}if(!path.startsWith("/")){setWriteStatus("Absolute Path 必须是绝对路径","error");return;}if(project&&!/^[A-Za-z0-9_-]{1,64}$/.test(project)){setWriteStatus("Project ID 只能包含字母、数字、_、-，最长 64 个字符","error");return;}if((exec||commit)&&!write){setWriteStatus("exec / commit 需要 write","error");return;}if(mutation&&(!write||!exec)){setWriteStatus("git rw 需要 write + exec","error");return;}const button=form.querySelector("button[type=submit]");button.disabled=true;button.textContent="保存中…";setWriteStatus("正在写入 config.toml…","pending");try{const result=await sendJson("/api/projects","POST",{expected_revision:configRevision,workspace,project:project||null,path,allow_write:write,allow_exec:exec,allow_git_commit:commit,allow_git_mutation:mutation,allow_git_push:push});$("add-project-id").value="";$("add-project-path").value="";const target=`${result.project?.workspace||workspace}/${result.project?.id||project||"project"}`;setWriteStatus(result.requires_restart?`已保存 ${target}，但热重载未生效：${result.reload_warning||"需要重启 EndlessVibe"}`:`已保存 ${target} 并已热生效`,result.requires_restart?"pending":"success");await refreshProjects();}catch(error){const message=error.status===409?"配置已变化，已刷新，请重新填写后保存":error.message;setWriteStatus(`保存失败：${message}`,"error");if(error.status===409)await refreshProjects();}finally{button.disabled=false;button.textContent="保存并添加";}}
async function handlePermissionSubmit(event){const form=event.target.closest(".project-permission-form");if(!form)return;event.preventDefault();const inputs=Object.fromEntries([...form.querySelectorAll("input[data-permission]")].map(input=>[input.dataset.permission,input.checked]));if((inputs.exec||inputs.commit)&&!inputs.write){setWriteStatus("exec / commit 需要 write","error");return;}if(inputs.mutation&&(!inputs.write||!inputs.exec)){setWriteStatus("git rw 需要 write + exec","error");return;}const button=form.querySelector("button");button.disabled=true;setWriteStatus(`正在更新 ${form.dataset.workspace}/${form.dataset.project}…`,"pending");try{const result=await sendJson(`/api/projects/${encodeURIComponent(form.dataset.workspace)}/${encodeURIComponent(form.dataset.project)}`,"PATCH",{expected_revision:configRevision,allow_write:inputs.write,allow_exec:inputs.exec,allow_git_commit:inputs.commit,allow_git_mutation:inputs.mutation,allow_git_push:inputs.push});setWriteStatus(result.requires_restart?`权限已写入，但热重载未生效：${result.reload_warning||"需要重启 EndlessVibe"}`:"权限已写入并已热生效",result.requires_restart?"pending":"success");await refreshProjects();}catch(error){setWriteStatus(error.status===409?"配置已变化，已刷新，请重试":`保存失败：${error.message}`,"error");if(error.status===409)await refreshProjects();}finally{button.disabled=false;}}
async function handleSandboxCheck(){const button=$("sandbox-check"),status=$("sandbox-check-status");if(!button)return;button.disabled=true;button.textContent="Checking…";if(status){status.textContent="正在创建基础 bubblewrap namespace 并检查工具可见性…";status.className="write-status pending";}try{const data=await getJson("/api/sandbox");renderSandboxDiagnostics(data);const missing=(data.diagnostics?.programs||[]).filter(p=>p.required&&p.status!=="available");if(status){status.textContent=missing.length?`缺失 required programs: ${missing.map(p=>p.program).join(", ")}`:"Sandbox required programs 可见";status.className=`write-status ${missing.length?"error":"success"}`;}}catch(error){if(status){status.textContent=`Sandbox diagnostics 失败：${error.message}`;status.className="write-status error";}}finally{button.disabled=false;button.textContent="Check Sandbox";}}
async function handleStorageMaintenance(){const button=$("storage-maintenance"),status=$("storage-maintenance-status");if(!button)return;button.disabled=true;button.textContent="Maintaining…";if(status){status.textContent="正在执行受限 retention cleanup…";status.className="write-status pending";}try{const result=await sendJson("/api/storage/maintenance","POST",{});if(status){status.textContent=`已完成：删除 ${result.deleted?.total??0} 条记录；未执行 VACUUM`;status.className="write-status success";}await refreshStorage();}catch(error){if(status){status.textContent=`Maintenance 失败：${error.message}`;status.className="write-status error";}}finally{button.disabled=false;button.textContent="Run maintenance";}}
async function handleConfigReload(){const button=$("config-reload");if(!button)return;button.disabled=true;button.textContent="Reloading…";setReloadStatus("正在重新验证并加载 Workspace / Project 授权…","pending");try{const result=await sendJson("/api/config/reload","POST",{});setReloadStatus(`已热重载 config revision ${String(result.revision||"").slice(0,12)} · ${result.workspace_count??0} workspaces · ${result.project_count??0} projects`,"success");await Promise.all([refreshConfig(),refreshStatus()]);}catch(error){setReloadStatus(error.code==="RELOAD_RESTART_REQUIRED"?`无法热重载：${error.message}`:`Reload 失败：${error.message}`,"error");await refreshConfig().catch(()=>{});}finally{button.disabled=false;button.textContent="Reload project config";}}
activatePage();setText("site-origin",location.origin);
$("refresh")?.addEventListener("click",refresh);
$("add-project-form")?.addEventListener("submit",handleAddProject);
$("workspace-config")?.addEventListener("submit",handlePermissionSubmit);
$("config-reload")?.addEventListener("click",handleConfigReload);
$("sandbox-check")?.addEventListener("click",handleSandboxCheck);
$("storage-maintenance")?.addEventListener("click",handleStorageMaintenance);
$("expand-all-operations")?.addEventListener("click",expandAllOperations);
$("collapse-all-operations")?.addEventListener("click",collapseAllOperations);
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&hiddenDirty){hiddenDirty=false;pendingEvents.clear();refresh();}});
window.addEventListener("online",()=>{refresh();if(!eventSource||eventSource.readyState===EventSource.CLOSED)connectEvents();});
window.addEventListener("beforeunload",()=>eventSource?.close());
if("ResizeObserver"in window)new ResizeObserver(resizePlots).observe(document.querySelector(".shell"));else window.addEventListener("resize",resizePlots);
setInterval(()=>{if(serviceOnline&&uptimeReceivedAt)setText("uptime",formatUptime(uptimeSnapshot+Math.floor((Date.now()-uptimeReceivedAt)/1000)));},1000);
refresh().finally(connectEvents);
