"use strict";
const $=id=>document.getElementById(id);
const currentPage=location.pathname==="/activity"?"activity":location.pathname==="/operations"?"operations":location.pathname==="/config"?"config":"home";
const pageNames={home:"首页",activity:"活动",operations:"操作日志",config:"配置"};
const plots=new Map(),pendingEvents=new Set();
let busy=false,eventSource=null,eventRefreshTimer=null,hiddenDirty=false,serviceOnline=false,configRevision="",uptimeSnapshot=0,uptimeReceivedAt=0;
const dateTime=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false});
const timeOnly=new Intl.DateTimeFormat("zh-CN",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false});
const setText=(id,value)=>{const el=$(id);if(el)el.textContent=value??"—";};
const formatTime=seconds=>dateTime.format(new Date(seconds*1000));
const formatShortTime=seconds=>timeOnly.format(new Date(seconds*1000));
function formatUptime(seconds){const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60),secs=seconds%60;return (days?`${days}天 `:"")+`${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(secs).padStart(2,"0")}`;}
function formatBytes(value){let n=Number(value)||0;const units=["B","KiB","MiB","GiB","TiB"];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return `${n>=100||i===0?n.toFixed(0):n>=10?n.toFixed(1):n.toFixed(2)} ${units[i]}`;}
function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el;}
function activatePage(){document.querySelectorAll("[data-page]").forEach(el=>el.hidden=el.dataset.page!==currentPage);document.querySelectorAll("[data-nav]").forEach(el=>el.classList.toggle("active",el.dataset.nav===currentPage));setText("breadcrumb-current",pageNames[currentPage]);document.title=`EndlessVibe · ${pageNames[currentPage]}`;}
function setConnection(online,label){serviceOnline=online;const badge=$("header-status");if(!badge)return;badge.className=`header-status ${online?"online":"offline"}`;setText("header-status-text",label||(online?"运行中":"离线"));}
function renderToolChips(id,tools){const host=$(id);if(!host)return;host.replaceChildren();for(const tool of tools||[])host.appendChild(node("span","tool-chip",tool));if(!(tools||[]).length)host.appendChild(node("span","empty-inline","暂无工具"));}
function chartTheme(){const s=getComputedStyle(document.documentElement);return{muted:s.getPropertyValue("--muted").trim(),border:s.getPropertyValue("--border").trim(),accent:s.getPropertyValue("--accent").trim(),red:s.getPropertyValue("--red").trim(),blue:s.getPropertyValue("--blue").trim(),amber:s.getPropertyValue("--amber").trim(),violet:s.getPropertyValue("--violet").trim()};}
function chartOptions(host,series,height=270,yFormatter=null){const c=chartTheme(),xAxis={stroke:c.muted,grid:{stroke:c.border,width:1},ticks:{stroke:c.border,width:1},font:"11px system-ui"},yAxis={stroke:c.muted,grid:{stroke:c.border,width:1},ticks:{stroke:c.border,width:1},font:"11px system-ui"};if(yFormatter)yAxis.values=(_,values)=>values.map(yFormatter);return{width:Math.max(280,Math.floor(host.clientWidth)),height,scales:{x:{time:true},y:{auto:true}},axes:[xAxis,yAxis],series,legend:{show:true},cursor:{drag:{x:true,y:false,setScale:true}}};}
function upsertPlot(key,hostId,data,series,height=270,yFormatter=null){const host=$(hostId);if(!host||host.hidden||host.clientWidth===0)return;const existing=plots.get(key);if(existing){existing.setData(data);return;}plots.set(key,new uPlot(chartOptions(host,series,height,yFormatter),data,host));}
function renderMetrics(data){const totals=data.totals||{},points=data.points||[];for(const prefix of ["home","activity"]){setText(`${prefix}-requests`,totals.requests??0);setText(`${prefix}-success`,totals.successes??0);setText(`${prefix}-failed`,totals.failures??0);setText(`${prefix}-http-requests`,totals.http_requests??0);setText(`${prefix}-rx`,formatBytes(totals.rx_bytes));setText(`${prefix}-tx`,formatBytes(totals.tx_bytes));}if(!points.length||!window.uPlot)return;const times=points.map(p=>p.time),requests=points.map(p=>p.requests),successes=points.map(p=>p.successes),failures=points.map(p=>p.failures),active=points.map(p=>p.active_jobs),rx=points.map(p=>p.rx_bytes),tx=points.map(p=>p.tx_bytes),c=chartTheme();const toolSeries=[{}, {label:"Requests",stroke:c.blue,width:2,points:{show:false}}, {label:"Success",stroke:c.accent,width:2,points:{show:false}}, {label:"Failed",stroke:c.red,width:2,points:{show:false}}];const trafficSeries=[{}, {label:"RX",stroke:c.violet,width:2,points:{show:false},value:(_,v)=>v==null?"—":formatBytes(v)}, {label:"TX",stroke:c.amber,width:2,points:{show:false},value:(_,v)=>v==null?"—":formatBytes(v)}];const jobsSeries=[{}, {label:"Active Jobs",stroke:c.amber,width:2,points:{show:false}}];if(currentPage==="home"){upsertPlot("home-tool","home-tool-chart",[times,requests,successes,failures],toolSeries,245);upsertPlot("home-traffic","home-traffic-chart",[times,rx,tx],trafficSeries,245,formatBytes);}if(currentPage==="activity"){upsertPlot("activity-tool","activity-tool-chart",[times,requests,successes,failures],toolSeries,285);upsertPlot("activity-jobs","activity-jobs-chart",[times,active],jobsSeries,285);upsertPlot("activity-traffic","activity-traffic-chart",[times,rx,tx],trafficSeries,285,formatBytes);setText("activity-updated",`更新于 ${formatTime(data.generated_at)} · ${data.bucket_seconds}s/点`);}}
function outcomeClass(outcome){return ["succeeded","running","accepted"].includes(outcome)?"good":["failed","timed_out","cancelled","interrupted"].includes(outcome)?"bad":"neutral";}
function renderAudits(id,audits,limit){const host=$(id);if(!host)return;host.replaceChildren();const rows=(audits||[]).slice(0,limit);if(!rows.length){host.className="activity-list empty-state";host.textContent="暂无活动";return;}host.className="activity-list";for(const item of rows){const row=node("div","activity-row"),main=node("div","activity-main"),meta=node("div","activity-meta");main.append(node("strong","activity-tool",item.tool||"—"),node("span","activity-target",item.workspace||"—"));meta.append(node("span",`state ${outcomeClass(item.outcome)}`,item.outcome||"—"),node("time","",formatShortTime(item.time)));row.append(main,meta);host.appendChild(row);}}
function renderJobs(id,jobs,limit){const host=$(id);if(!host)return;host.replaceChildren();const rows=(jobs||[]).slice(0,limit);if(!rows.length){host.className="activity-list empty-state";host.textContent="暂无任务";return;}host.className="activity-list";for(const item of rows){const row=node("div","activity-row"),main=node("div","activity-main"),meta=node("div","activity-meta"),target=item.project?`${item.workspace}/${item.project}`:item.workspace||"—";main.append(node("strong","activity-tool",item.program||"—"),node("span","activity-target",target));meta.append(node("span",`state ${outcomeClass(item.status)}`,item.status||"—"),node("time","",formatShortTime(item.created)));row.append(main,meta);host.appendChild(row);}}
function operationTarget(item){return item.workspace?(item.project?`${item.workspace}/${item.project}`:item.workspace):"service";}
function compactJson(value,max=520){let text;try{text=JSON.stringify(value??{},null,2);}catch{text=String(value??"");}return text.length>max?`${text.slice(0,max)}\n…`:text;}
function compactDiff(item){const count=(item.added_lines||item.removed_lines)?`+${item.added_lines||0} -${item.removed_lines||0}\n`:"";const diff=String(item.diff_preview||"");if(!diff)return count||"—";const text=count+diff;return text.length>760?`${text.slice(0,760)}\n…`:text;}
function renderOperations(items){const host=$("operation-list");if(!host)return;const openIds=new Set([...host.querySelectorAll("details[open]")].map(el=>el.dataset.id));const previousScroll=host.scrollTop;const atTop=previousScroll<24;host.replaceChildren();if(!(items||[]).length){host.className="operation-stream empty-state";host.textContent="暂无操作日志";return;}host.className="operation-stream";for(const item of items){const details=node("details","operation-entry timeline-entry");details.dataset.id=String(item.seq);const summary=node("summary","operation-summary-grid");const timeline=node("div","operation-timeline-cell"),time=node("time","operation-time",formatShortTime(item.started)),dot=node("span",`timeline-dot ${outcomeClass(item.status)}`);timeline.append(time,dot);const operation=node("div","operation-id-cell"),id=node("strong","operation-id",`#${item.seq}`),tool=node("span","operation-tool",item.tool||"—"),target=node("span","operation-target",operationTarget(item)),meta=node("span","operation-inline-meta",`${item.status||"—"} · ${item.duration_ms||0} ms`);operation.append(id,tool,target,meta);const input=node("pre","operation-cell-preview input-preview");input.textContent=compactJson(item.input_preview);const diff=node("pre","operation-cell-preview diff-preview");diff.textContent=compactDiff(item);summary.append(timeline,operation,input,diff);const body=node("div","operation-detail operation-loading","展开后加载完整 Input / Diff / Output…");details.append(summary,body);details.addEventListener("toggle",()=>{if(details.open&&!details.dataset.loaded)loadOperationDetail(details);});if(openIds.has(String(item.seq))){details.open=true;queueMicrotask(()=>loadOperationDetail(details));}host.appendChild(details);}host.scrollTop=atTop?0:previousScroll;}
function jsonSection(title,value){const section=node("section","operation-section"),heading=node("h4","",title),pre=node("pre","operation-json");pre.textContent=JSON.stringify(value??{},null,2);section.append(heading,pre);return section;}
function diffSection(diff){const section=node("section","operation-section"),heading=node("h4","","Diff"),pre=node("pre","operation-diff");for(const line of String(diff||"").split("\n")){let cls="diff-context";if(line.startsWith("+")&&!line.startsWith("+++"))cls="diff-add";else if(line.startsWith("-")&&!line.startsWith("---"))cls="diff-remove";else if(line.startsWith("@@")||line.startsWith("---")||line.startsWith("+++"))cls="diff-meta";const span=node("span",cls,line);pre.appendChild(span);pre.appendChild(document.createTextNode("\n"));}section.append(heading,pre);return section;}
async function loadOperationDetail(details){if(details.dataset.loaded==="loading"||details.dataset.loaded==="true")return;details.dataset.loaded="loading";const body=details.querySelector(".operation-detail");body.className="operation-detail operation-loading";body.textContent="加载详情…";try{const detail=await getJson(`/api/operations/${encodeURIComponent(details.dataset.id)}`);body.replaceChildren();body.className="operation-detail timeline-detail";const meta=node("div","operation-detail-meta");for(const [label,value] of [["Operation",`#${detail.seq}`],["Started",formatTime(detail.started)],["Finished",detail.finished?formatTime(detail.finished):"—"],["Duration",`${detail.duration_ms||0} ms`],["Target",operationTarget(detail)]]){const item=node("div","");item.append(node("span","",label),node("strong","",value));meta.appendChild(item);}body.appendChild(meta);const primary=node("div","operation-detail-primary");primary.append(jsonSection("Input",detail.input),detail.diff?diffSection(detail.diff):jsonSection("Diff",{"changed":false}));body.appendChild(primary);const secondary=node("div","operation-detail-secondary");secondary.append(jsonSection("Output",detail.output));if(detail.error){const errorSection=node("section","operation-section operation-error"),heading=node("h4","","Error"),pre=node("pre","operation-json");pre.textContent=detail.error;errorSection.append(heading,pre);secondary.appendChild(errorSection);}body.appendChild(secondary);const jobId=detail.output?.job_id;if(jobId){const jobSection=node("section","operation-section"),heading=node("h4","","Job Output"),pre=node("pre","operation-job-output","加载任务输出…");jobSection.append(heading,pre);body.appendChild(jobSection);try{const job=await getJson(`/api/jobs/${encodeURIComponent(jobId)}`);pre.textContent=job.output?.output||"(no output)";const state=node("div","job-detail-state",`status: ${job.job?.status||"—"} · exit: ${job.job?.exit_code??"—"}`);jobSection.insertBefore(state,pre);}catch(error){pre.textContent=error.message;}}details.dataset.loaded="true";}catch(error){body.className="operation-detail operation-error";body.textContent=error.message;details.dataset.loaded="";}}
function expandAllOperations(){document.querySelectorAll("#operation-list details.operation-entry").forEach(details=>{details.open=true;});}
function collapseAllOperations(){document.querySelectorAll("#operation-list details.operation-entry").forEach(details=>{details.open=false;});}
function displayValue(value){if(Array.isArray(value))return value.length?value.join(", "):"—";if(typeof value==="boolean")return value?"启用":"禁用";if(value===null||value===undefined||value==="")return"—";return String(value);}
function renderConfigList(id,rows){const host=$(id);if(!host)return;host.replaceChildren();for(const [label,value] of rows){const wrap=node("div","config-row");wrap.append(node("dt","",label),node("dd","mono-value",displayValue(value)));host.appendChild(wrap);}}
function permissionToggle(key,checked,label=key){const wrapper=node("label","permission-toggle");const input=document.createElement("input");input.type="checkbox";input.checked=!!checked;input.dataset.permission=key;wrapper.append(input,document.createTextNode(` ${label}`));return wrapper;}
function renderWorkspaceConfig(workspaces){const host=$("workspace-config");if(!host)return;host.replaceChildren();for(const workspace of workspaces||[]){const card=node("article","workspace-card"),head=node("div","workspace-head"),title=node("div");title.append(node("strong","",workspace.id),node("span","mono-value",workspace.path));head.append(title,node("span","count-badge",`${workspace.project_count} projects`));card.appendChild(head);const projects=node("div","project-list");for(const project of workspace.projects||[]){const row=node("div","project-row"),left=node("div"),form=node("form","permission-editor project-permission-form");left.append(node("strong","",project.id),node("span","mono-value",project.path));form.dataset.workspace=workspace.id;form.dataset.project=project.id;form.append(permissionToggle("write",project.allow_write),permissionToggle("exec",project.allow_exec),permissionToggle("commit",project.allow_git_commit),permissionToggle("mutation",project.allow_git_mutation,"git rw"));const save=node("button","small-button","保存");save.type="submit";form.appendChild(save);row.append(left,form);projects.appendChild(row);}card.appendChild(projects);host.appendChild(card);}if(!(workspaces||[]).length)host.textContent="暂无 Workspace";}
function renderWorkspaceOptions(workspaces){const select=$("add-project-workspace");if(!select)return;const selected=select.value;select.replaceChildren();for(const workspace of workspaces||[]){const option=document.createElement("option");option.value=workspace.id;option.textContent=`${workspace.id} — ${workspace.path}`;select.appendChild(option);}if([...select.options].some(o=>o.value===selected))select.value=selected;}
function renderConfig(data){configRevision=data.revision||"";renderConfigList("config-server",[["Bind",data.server?.bind],["Public URL",data.server?.public_url],["Allowed Hosts",data.server?.allowed_hosts],["Dashboard",data.dashboard?.listen_address],["Local Only",data.dashboard?.local_only]]);renderConfigList("config-security",[["Authentication",data.security?.authentication],["HTTP Loopback",data.security?.allow_http_loopback],["Access Token",`${data.security?.access_token_seconds??0}s`],["Refresh Token",`${data.security?.refresh_token_seconds??0}s`],["Extra Redirect URIs",data.security?.extra_redirect_uri_count]]);renderConfigList("config-execution",[["Backend",data.execution?.backend],["Shell",data.execution?.allow_shell],["Network",data.execution?.allow_network],["Bubblewrap",data.execution?.bubblewrap],["PATH",data.execution?.path],["Memory",`${data.execution?.memory_limit_mb??0} MiB`],["Max Processes",data.execution?.max_processes],["Allowed Programs",data.execution?.allowed_programs],["Readonly Mounts",(data.execution?.readonly_mounts||[]).map(m=>`${m.source} → ${m.target}`)]]);renderConfigList("config-limits",[["Max File",formatBytes(data.limits?.max_file_bytes)],["Max Read",formatBytes(data.limits?.max_read_bytes)],["Max Output",formatBytes(data.limits?.max_output_bytes)],["Command Timeout",`${data.limits?.command_timeout_seconds??0}s`],["Max Jobs",data.limits?.max_jobs],["Retained Jobs",data.limits?.retained_jobs],["Search Max Files",data.limits?.search_max_files],["Search Max Bytes",formatBytes(data.limits?.search_max_bytes)]]);renderConfigList("config-git",[["Executable",data.git?.executable],["Author",data.git?.author_name],["Email",data.git?.author_email]]);renderWorkspaceConfig(data.workspaces);renderWorkspaceOptions(data.workspaces);setText("mcp-tool-count",`${data.mcp?.tool_count??0} tools`);renderToolChips("mcp-tools",data.mcp?.tools||[]);const badge=$("config-restart-badge");if(badge){badge.textContent=data.requires_restart?"Pending restart":"已生效";badge.classList.toggle("pending-restart",!!data.requires_restart);}}
function renderStatus(data){setConnection(true);uptimeSnapshot=data.uptime_seconds||0;uptimeReceivedAt=Date.now();setText("version",`v${data.version}`);setText("uptime",formatUptime(uptimeSnapshot));setText("workspace-count",data.workspace_count);setText("project-count",data.project_count);setText("active-jobs",data.active_jobs);setText("execution-backend",data.security?.execution_backend);setText("status-title","服务运行正常");setText("status-detail","MCP 与本地 Dashboard 均已响应；实时更新由 SSE 事件驱动。");setText("last-success",`最近成功检查：${formatTime(data.checked_at_unix_seconds)}`);setText("home-auth",data.security?.authentication);setText("home-shell",data.security?.shell_enabled?"启用":"禁用");setText("home-network",data.security?.network_enabled?"启用":"禁用");setText("home-tool-count",Array.isArray(data.mcp?.tools)?data.mcp.tools.length:"—");renderToolChips("home-mcp-tools",data.mcp?.tools||[]);}
async function getJson(url,signal){const response=await fetch(url,{cache:"no-store",headers:{Accept:"application/json"},signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data.error||`${url} HTTP ${response.status}`),{status:response.status});return data;}
async function sendJson(url,method,body){const response=await fetch(url,{method,cache:"no-store",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data.error||`${method} ${url} HTTP ${response.status}`),{status:response.status});return data;}
async function refreshStatus(){renderStatus(await getJson("/api/status"));}
async function refreshMetrics(){renderMetrics(await getJson("/api/metrics"));}
async function refreshActivity(){const activity=await getJson("/api/activity");renderAudits("home-activity-list",activity.audits,8);setText("home-activity-updated",`更新于 ${formatShortTime(activity.generated_at)}`);if(currentPage==="activity"){renderAudits("audit-list",activity.audits,40);renderJobs("job-list",activity.jobs,30);}}
async function refreshOperations(){if(currentPage!=="operations")return;const data=await getJson("/api/operations?limit=100");renderOperations(data.operations);setText("operation-updated",`更新于 ${formatShortTime(data.generated_at)}`);}
async function refreshConfig(){renderConfig(await getJson("/api/config"));}
async function refresh(){if(busy)return;busy=true;const button=$("refresh");if(button){button.disabled=true;button.textContent="刷新中…";}try{await refreshStatus();if(currentPage==="home")await Promise.all([refreshMetrics(),refreshActivity()]);if(currentPage==="activity")await Promise.all([refreshMetrics(),refreshActivity()]);if(currentPage==="operations")await refreshOperations();if(currentPage==="config")await refreshConfig();}catch(error){setConnection(false);setText("status-title","暂时无法获取状态");setText("status-detail",error.message);}finally{busy=false;if(button){button.disabled=false;button.textContent="立即刷新";}}}
async function refreshForEvents(types){try{const tasks=[];if(types.has("job_changed"))tasks.push(refreshStatus());if(currentPage==="home"||currentPage==="activity"){if(types.has("metrics_changed")||types.has("activity_changed")||types.has("job_changed"))tasks.push(refreshMetrics());if(types.has("activity_changed")||types.has("job_changed"))tasks.push(refreshActivity());}if(currentPage==="operations"&&types.has("operation_created"))tasks.push(refreshOperations());if(currentPage==="config"&&types.has("config_changed"))tasks.push(refreshConfig());await Promise.all(tasks);}catch(error){setConnection(false,"事件刷新失败");}}
function scheduleEventRefresh(type){pendingEvents.add(type);if(document.hidden){hiddenDirty=true;return;}clearTimeout(eventRefreshTimer);eventRefreshTimer=setTimeout(()=>{const types=new Set(pendingEvents);pendingEvents.clear();refreshForEvents(types);},180);}
function connectEvents(){if(!("EventSource"in window)){setInterval(()=>{if(!document.hidden)refresh();},5000);return;}eventSource?.close();eventSource=new EventSource("/api/events");eventSource.onopen=()=>{if(serviceOnline)setConnection(true,"运行中 · SSE");};eventSource.onmessage=event=>{try{const message=JSON.parse(event.data);if(message?.type)scheduleEventRefresh(message.type);}catch{}};eventSource.onerror=()=>{if(serviceOnline)setConnection(true,"SSE 重连中");};}
async function handleAddProject(event){event.preventDefault();const write=$("add-project-write").checked,exec=$("add-project-exec").checked,commit=$("add-project-commit").checked,mutation=$("add-project-git-mutation").checked;if((exec||commit)&&!write){setText("config-write-status","exec/commit 需要 write");return;}if(mutation&&(!write||!exec)){setText("config-write-status","git rw 需要 write + exec");return;}const button=event.currentTarget.querySelector("button[type=submit]");button.disabled=true;setText("config-write-status","写入中…");try{await sendJson("/api/projects","POST",{expected_revision:configRevision,workspace:$("add-project-workspace").value,project:$("add-project-id").value.trim()||null,path:$("add-project-path").value.trim(),allow_write:write,allow_exec:exec,allow_git_commit:commit,allow_git_mutation:mutation});$("add-project-id").value="";$("add-project-path").value="";setText("config-write-status","已写入，重启后生效");await refreshConfig();}catch(error){setText("config-write-status",error.status===409?"配置已变化，已刷新，请重试":error.message);if(error.status===409)await refreshConfig();}finally{button.disabled=false;}}
async function handlePermissionSubmit(event){const form=event.target.closest(".project-permission-form");if(!form)return;event.preventDefault();const inputs=Object.fromEntries([...form.querySelectorAll("input[data-permission]")].map(input=>[input.dataset.permission,input.checked]));if((inputs.exec||inputs.commit)&&!inputs.write){setText("config-write-status","exec/commit 需要 write");return;}if(inputs.mutation&&(!inputs.write||!inputs.exec)){setText("config-write-status","git rw 需要 write + exec");return;}const button=form.querySelector("button");button.disabled=true;setText("config-write-status",`更新 ${form.dataset.workspace}/${form.dataset.project}…`);try{await sendJson(`/api/projects/${encodeURIComponent(form.dataset.workspace)}/${encodeURIComponent(form.dataset.project)}`,"PATCH",{expected_revision:configRevision,allow_write:inputs.write,allow_exec:inputs.exec,allow_git_commit:inputs.commit,allow_git_mutation:inputs.mutation});setText("config-write-status","权限已写入，重启后生效");await refreshConfig();}catch(error){setText("config-write-status",error.status===409?"配置已变化，已刷新，请重试":error.message);if(error.status===409)await refreshConfig();}finally{button.disabled=false;}}
function resizePlots(){for(const [key,plot] of plots){const host=plot.root?.parentElement;if(host&&host.clientWidth>0)plot.setSize({width:Math.max(280,Math.floor(host.clientWidth)),height:key.startsWith("home-")?245:285});}}
activatePage();setText("site-origin",location.origin);
$("refresh")?.addEventListener("click",refresh);
$("add-project-form")?.addEventListener("submit",handleAddProject);
$("workspace-config")?.addEventListener("submit",handlePermissionSubmit);
$("expand-all-operations")?.addEventListener("click",expandAllOperations);
$("collapse-all-operations")?.addEventListener("click",collapseAllOperations);
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&hiddenDirty){hiddenDirty=false;pendingEvents.clear();refresh();}});
window.addEventListener("online",()=>{refresh();if(!eventSource||eventSource.readyState===EventSource.CLOSED)connectEvents();});
window.addEventListener("beforeunload",()=>eventSource?.close());
if("ResizeObserver"in window)new ResizeObserver(resizePlots).observe(document.querySelector(".shell"));else window.addEventListener("resize",resizePlots);
setInterval(()=>{if(serviceOnline&&uptimeReceivedAt)setText("uptime",formatUptime(uptimeSnapshot+Math.floor((Date.now()-uptimeReceivedAt)/1000)));},1000);
refresh().finally(connectEvents);
